### ISSUE TITLE
When will this project be live/moved off of testnet?

### ISSUE THREAD

**Issue by ghost** [theQRL/QRL#1008]
Title pretty much explains it :)

I'd love to be running this live currently. I can pull about 1Kh/s on cryptonight.

I'm very interested in the project, is there any plan to become listed on the exchanges/curious about what dates if there is any timeframe on when the project will be live.

Thanks!!! 💃

**Comment by jleni** [comment]
Hi @juanzolo,
Thank you very much for your interest.
We try to use GitHub only for technical issues.

We invite you to ask these questions and to connect with our community in Discord. You can join using the following link https://discord.gg/sxFGEJ
