### ISSUE TITLE
Aborted (core dumped) when running start_qrl

### ISSUE THREAD

**Issue by hdelatorre** [theQRL/QRL#1031]
consistently receive this error:

python3: /usr/include/boost/multiprecision/cpp_int.hpp:1236: void boost::multiprecision::backends::cpp_int_backend<MinBits, MaxBits, SignType, Checked, Allocator>::do_assign_arithmetic(long double, const false_&) [with unsigned int MinBits = 0u; unsigned int MaxBits = 0u; boost::multiprecision::cpp_integer_type SignType = (boost::multiprecision::cpp_integer_type)1u; boost::multiprecision::cpp_int_check_type Checked = (boost::multiprecision::cpp_int_check_type)0u; Allocator = std::allocator<long long unsigned int>; mpl_::false_ = mpl_::bool_<false>]: Assertion `!(boost::math::isnan)(a)' failed.
Aborted (core dumped)

This is on an AWS hosted instance.  Tried multiple times with fresh instances:

AMI ID: ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180126 (ami-66506c1c)

instance type: m5.2xlarge

from a fresh instance I ran these commands:

ubuntu@ip-10-86-3-32:~$ history
    1  sudo apt update && sudo apt upgrade -y
    2  sudo apt-get -y install swig3.0 python3-dev python3-pip build-essential cmake pkg-config libssl-dev libffi-dev libhwloc-dev libboost-dev
    3  pip3 install -U qrl
    4  qrl wallet_gen
    5  qrl -r --host 104.237.3.185 slave_tx_generate
    6  mkdir .qrl
    7  cp slaves.json .qrl/
    8  start_qrl

**Comment by ghost** [comment]
Same problem
did you manage to fix this ?

root@AyyPT01:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
root@AyyPT01:~# gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@AyyPT01:~# g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

All dependencies installed and doubled checked.
Repo cloned from source.

**Comment by jleni** [comment]
Tested with 
https://hub.docker.com/_/ubuntu/
Docker Image ubuntu:xenial

I could not reproduce the problem. I will keep investigating.
It has been reported that it was possible to reproduce using Ubuntu via WSL in Windows 10

**Comment by jleni** [comment]
@jplomas: I've just tried installing in Windows 10 WSL (Ubuntu) and I could not reproduce the problem. 
@GasGeverij I used identical compilers (gcc/g++), It seems unlikely is related to that. I should have had the same problem.

I will move to setting up an AWS machine as per @hdelatorre repro steps

**Comment by ghost** [comment]
Mine was on a vultr.com machine

**Comment by jleni** [comment]
So I've tested 0.62.4 in AWS 

Instance-type: t2.micro
AMI ID: ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180222-d83d0782-cb94-46d7-8993-f4ce15d1a484-ami-ee4eac93.4 (ami-f6cef993)

Followed the instructions and it seems to be working well. I have not seen any core dump.
It is a tiny bit newer AMI but I dont think that is something significant.

**Comment by ghost** [comment]
Yeah cyy also indicated it works fine on AWS, rather not eveyone has a credit card.
It's something with vultr and probably virtual ocean since i think vultr is a resseler of dg.

**Comment by jleni** [comment]
I will try with vultr later today then.
Any specific configuration you would suggest me to try?

**Comment by ghost** [comment]
Not really, eveything was just updated, and qrl was pulled from source.

**Comment by jleni** [comment]
Fixed in https://github.com/theQRL/qryptonight/pull/47.

The fix will be available in the next release.

**Comment by jleni** [comment]
@GasGeverij so I could reproduce the bug in a vultr host. 

Oddly enough, it was not happening in the 1CPU+1024MB. I managed to have the crash in a 4CPU+8192MB host.

The fix will come with 0.63.x that is planned to be released in a few more days.
