### ISSUE TITLE
QRL Nodes failing. Need fix

### ISSUE THREAD

**Issue by ksangsu95** [theQRL/QRL#1036]
The ip addresses for qrl nodes keep on failing. I will attach the specification below. *Currently running on Ubuntu OS via windows 10 WSL. Apparently the first ip address stated '104.237.3.185' is the only one with the successful connections and furthermore when I attempted to create a slaves.json file, it makes an error. 

The error is displayed like this:

ksangsu95@4ghzM1:~$ qrl -r --host 104.237.3.185 slave_tx_generate
Src []: 0106005f9c0100a1cf8dd9bc6f453c8c6c0fc0a878be4e4e48297d5b661c753802365cd663afe5
Addr from (Leave blank in case same as source) []:
Number of slaves [0]: 4
Access type [0]: 0
Fee [0.0]: 0
Error validating arguments

-------------------------------------------------------------------------------------------------------------------
# Current state of QRL Nodes IP addresses 14/03/2018 #

**104.237.3.185** 

:ksangsu95@4ghzM1:~$ nping -p 9000 104.237.3.185

Starting Nping 0.7.01 ( https://nmap.org/nping ) at 2018-03-14 14:45 STD
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #1): Protocol not available (92)
SENT (0.0025s) Starting TCP Handshake > 104.237.3.185:9000
RECV (0.1521s) Handshake with 104.237.3.185:9000 completed
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #2): Protocol not available (92)
SENT (1.0062s) Starting TCP Handshake > 104.237.3.185:9000
RECV (1.1585s) Handshake with 104.237.3.185:9000 completed
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #3): Protocol not available (92)
SENT (2.0087s) Starting TCP Handshake > 104.237.3.185:9000
RECV (2.1606s) Handshake with 104.237.3.185:9000 completed
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #4): Protocol not available (92)
SENT (3.0106s) Starting TCP Handshake > 104.237.3.185:9000
RECV (3.1657s) Handshake with 104.237.3.185:9000 completed
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #5): Protocol not available (92)
SENT (4.0129s) Starting TCP Handshake > 104.237.3.185:9000
RECV (4.1658s) Handshake with 104.237.3.185:9000 completed

Max rtt: 155.322ms | Min rtt: 149.921ms | Avg rtt: 152.650ms
TCP connection attempts: 5 | Successful connections: 5 | Failed: 0 (0.00%)
Nping done: 1 IP address pinged in 4.17 seconds
**104.237.3.184**

:ksangsu95@4ghzM1:~$ nping -p 9000 104.237.3.184

Starting Nping 0.7.01 ( https://nmap.org/nping ) at 2018-03-14 14:46 STD
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #1): Protocol not available (92)
SENT (0.0027s) Starting TCP Handshake > 104.237.3.184:9000
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #2): Protocol not available (92)
SENT (1.0048s) Starting TCP Handshake > 104.237.3.184:9000
RECV (1.4806s) Possible TCP RST received from 104.237.3.184:9000 --> Connection refused
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #3): Protocol not available (92)
SENT (2.0071s) Starting TCP Handshake > 104.237.3.184:9000
RECV (2.4606s) Possible TCP RST received from 104.237.3.184:9000 --> Connection refused
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #4): Protocol not available (92)
SENT (3.0094s) Starting TCP Handshake > 104.237.3.184:9000
RECV (3.4654s) Possible TCP RST received from 104.237.3.184:9000 --> Connection refused
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #5): Protocol not available (92)
SENT (4.0123s) Starting TCP Handshake > 104.237.3.184:9000
RECV (4.4752s) Possible TCP RST received from 104.237.3.184:9000 --> Connection refused

Max rtt: N/A | Min rtt: N/A | Avg rtt: N/A
TCP connection attempts: 5 | Successful connections: 0 | Failed: 5 (100.00%)
Nping done: 1 IP address pinged in 5.02 seconds

**104.251.219.145**

:ksangsu95@4ghzM1:~$ nping -p 9000 104.251.219.145

Starting Nping 0.7.01 ( https://nmap.org/nping ) at 2018-03-14 14:46 STD
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #1): Protocol not available (92)
SENT (0.0024s) Starting TCP Handshake > 104.251.219.145:9000
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #2): Protocol not available (92)
SENT (1.0042s) Starting TCP Handshake > 104.251.219.145:9000
RECV (1.4505s) Possible TCP RST received from 104.251.219.145:9000 --> Connection refused
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #3): Protocol not available (92)
SENT (2.0052s) Starting TCP Handshake > 104.251.219.145:9000
RECV (2.4631s) Possible TCP RST received from 104.251.219.145:9000 --> Connection refused
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #4): Protocol not available (92)
SENT (3.0054s) Starting TCP Handshake > 104.251.219.145:9000
RECV (3.4506s) Possible TCP RST received from 104.251.219.145:9000 --> Connection refused
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #5): Protocol not available (92)
SENT (4.0058s) Starting TCP Handshake > 104.251.219.145:9000
RECV (4.4545s) Possible TCP RST received from 104.251.219.145:9000 --> Connection refused

Max rtt: N/A | Min rtt: N/A | Avg rtt: N/A
TCP connection attempts: 5 | Successful connections: 0 | Failed: 5 (100.00%)
Nping done: 1 IP address pinged in 5.01 seconds

**104.251.219.40**

:ksangsu95@4ghzM1:~$ nping -p 9000 104.251.219.40

Starting Nping 0.7.01 ( https://nmap.org/nping ) at 2018-03-14 14:47 STD
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #1): Protocol not available (92)
SENT (0.0030s) Starting TCP Handshake > 104.251.219.40:9000
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #2): Protocol not available (92)
SENT (1.0054s) Starting TCP Handshake > 104.251.219.40:9000
RECV (1.4787s) Possible TCP RST received from 104.251.219.40:9000 --> Connection refused
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #3): Protocol not available (92)
SENT (2.0080s) Starting TCP Handshake > 104.251.219.40:9000
RECV (2.4685s) Possible TCP RST received from 104.251.219.40:9000 --> Connection refused
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #4): Protocol not available (92)
SENT (3.0110s) Starting TCP Handshake > 104.251.219.40:9000
RECV (3.4565s) Possible TCP RST received from 104.251.219.40:9000 --> Connection refused
libnsock mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #5): Protocol not available (92)
SENT (4.0140s) Starting TCP Handshake > 104.251.219.40:9000
RECV (4.4685s) Possible TCP RST received from 104.251.219.40:9000 --> Connection refused

Max rtt: N/A | Min rtt: N/A | Avg rtt: N/A
TCP connection attempts: 5 | Successful connections: 0 | Failed: 5 (100.00%)
Nping done: 1 IP address pinged in 5.02 seconds

**Comment by cyyber** [comment]
The nping sends a different kind of data, which is not understood by gRPC this is why your connection was refused. You faced error validating argument while generating slave txn because you entered the wallet address into src instead of wallet index. Make sure you have wallet.qrl in the current working directory while you generate slave_tx
and instead of providing address into src, provide the wallet index.

You can check your wallet index, by using command
qrl wallet_ls

**Comment by ksangsu95** [comment]
Okay thanks!
