### ISSUE TITLE
PyScaffold version bomb

### ISSUE THREAD

**Issue by barrystyle** [theQRL/QRL#1046]
Seems to incorrectly detect setuptools being out of date, causing a cascading set of failures; preventing QRL (specifically pyqrllib and pyqryptonight) from being installed.

Hacking away the checks (and a seemingly obvious git submodule init/update) seems to result in a working installation..?

james

**Comment by jleni** [comment]
Could you provide log files about this? We have not seen this in any of our tests or reported before.

**Comment by cyyber** [comment]
The problem, sounds to me very similar to what Travis was facing few weeks before, even when setuptools was mentioned with latest version.

**Comment by barrystyle** [comment]
Apologies for the delay, just spun up a DigitalOcean Ubuntu 16.04 VPS to get a log for you guys.
I can't get around this (without hacking PyScafford's setup.py to remove the check).
[pyscaffold.log](https://github.com/theQRL/QRL/files/1824258/pyscaffold.log)
(putty seems to echo chars a few times by the way)

**Comment by cyyber** [comment]
Hmm.. I think error is similar to https://travis-ci.org/theQRL/QRL/jobs/354971598

**Comment by ghost** [comment]
Try uninstalling this:

``` sudo apt purge python-pkg-resources```

This should leave you with the python3 pkg resources.


If that doesn't work: 
To check the manual pkg for python (not python3):

```python -c 'import pkg_resources; print(pkg_resources.__file__)'```

Then remove it (maybe)
```sudo rm /usr/lib/python2.7/dist-packages/pkg_resources.py*```

Then attempt to install python3-pkg-resources

```sudo apt install python3-pkg-resources```

Source: https://askubuntu.com/questions/683601/how-to-upgrade-python-setuptools-12-2-on-ubuntu-15-04

**Comment by kstuart** [comment]
It's a compatibility issue with setuptools 39, an earlier version should work as a workaround for now, e.g: ```pip install "setuptools<39"```

Should be fixed in the next pyscaffold point release (3.0.2) in the next day or so.

Ref:
https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v3900
https://github.com/blue-yonder/pyscaffold/issues/148

**Comment by barrystyle** [comment]
Appears to be fine in master now?

**Comment by jleni** [comment]
yes, it seems it got fixed. We need to upgrade qrllib and test that everything is ok when upgrading. We are actually a few versions behind at the moment.
