### ISSUE TITLE
Moving transactions back to pool which are not the part of the mainchain

### ISSUE THREAD

**Issue by cyyber** [theQRL/QRL#1071]
Moving transactions which are the part of forked chain, back into transaction pool, so that the transactions which are not the part of the mainchain could be reprocessed.

**Comment by surg0r** [comment]
This should be added prior to mainnet. The reason this is important is that it is unlikely transactions are not on both sides of a typical fork.  However, in the event of a network failure with the p2p network fracturing and reconnecting it is possible transactions may be different on either branches of a fork.

XMSS is stateful and therefore it is critical that one-time signatures are not repeatedly replayed to expose an underlying private key, thus it is important that transactions are preserved during transition from main branch to fork branch and unduplicated transactions returned to the memory pool.

**Comment by cyyber** [comment]
Todo
- Pending Transactions need to be broadcasted to the node
- Number of transaction might be more than what pending pool can handle, so better take help of leveldb.

**Comment by cyyber** [comment]
Done in PR #1236
