### ISSUE TITLE
pip3 install qrl (not setting environment variable)

### ISSUE THREAD

**Issue by cyyber** [theQRL/QRL#1095]
pip3 install qrl
Even after the installation has been finished. It doesn't set environment variable. Due to which commands like start_qrl and qrl are not working.

All testnet users are temporarily using git clone

**Comment by cyyber** [comment]
I don't see proper installation at usr/local/lib/python3.6/dist-packages

**Comment by jleni** [comment]
@cyyber I think this has been fixed already. Should this issue be closed?
