### ISSUE TITLE
Win10 CPU Mining issue with xmr-stak v2.3.0

### ISSUE THREAD

**Issue by cyyber** [theQRL/QRL#1116]
As reported by wowo in Discord, his Result was rejected by the pool when he used CPU mining with xmr-stak v2.3.0

Although older versions are working fine for him.

OS: Windows 10

**Comment by jleni** [comment]
The most recent xmr-stak versions can now use the new monero PoW algorithm.
QRL <= 0.62.x still uses standard cryptonight
QRL >= 0.63.x will use the new monero7

if you want to use xmr-stak (2.4.2 at the moment), when running the configuration:
- For QRL <=0.62.x choose  cryptonight
- For QRL >=0.63.x choose monero7 

If you already have the configuration files, change the "currency" in pools.txt as described above
