### ISSUE TITLE
install qrl in virtualenv

### ISSUE THREAD

**Issue by sammy007** [theQRL/QRL#1122]
Using virtualenv:

```
pip3 install qrl
Collecting qrl
Installing collected packages: qrl
Successfully installed qrl-0.62.2
```

Indeed it must install tons of deps and also generate executables. But it does not. Either I am doing something wrong or something is broken in qrl package.

**Comment by cyyber** [comment]
Sorry, for the trouble. Our pip installer was broken, because of update in setup-tools not supporting older version of pyscaffold. We have updated our codebase and released the latest version. Please try installing latest version of qrl. It should work fine now.

**Comment by sammy007** [comment]
Great, it works now.
