### ISSUE TITLE
"start_qrl: command not found"

### ISSUE THREAD

**Issue by Ompanime** [theQRL/QRL#1134]
Ok, I ran into this issue in two separate times. Once when I was trying to run the new QRL testnet from source, and the other was after I tried a work-around in the clone.

I was told the team already new about the first issue and was working on a solution, so I'll just report the second one.

After attempting to clone the first time which didn't work (I'll report that issue separately), I tried a work-around suggested by a community member which was:
"From the bash prompt cd into your cloned QRL folder and issue the following commands:

sudo -H pip3 install virtualenv
virtualenv penv
source penv/bin/activate # this should add (penv) to your prompt
pip3 install -r requirements.txt
python setup.py install
start_qrl --miningCreditWallet <wallet address>"

All the commands worked fine until I put in the last one. This is what I put in, and what the terminal returned:

"(penv) Ompanime@DESKTOP-4H33NIU:~/qrl$ start_qrl --miningCreditWallet=Q0106001a5feb3ca2aa716eaa4667e8e5c1d6b34fe5917bbdd2843cff1c601f1fb06d903611dee8
start_qrl: command not found"

Please note that I am running a fresh installation of Ubuntu on Windows 10 Home ED through the WSL.

**Comment by cyyber** [comment]
Sorry, for the trouble. Our pip installer was broken, because of update in setup-tools not supporting older version of pyscaffold. We have updated our codebase and released the latest version. Please try installing latest version of qrl. It should work fine now.

**Comment by Ompanime** [comment]
It's working thanks!
