### ISSUE TITLE
NTP servers

### ISSUE THREAD

**Issue by kprimice** [theQRL/QRL#1156]
I try to use my own ntp server.
I updated config.yml with: `ntp_servers: ntp1.myntp.com`
After start_qrl I get:

> [Errno -2] Name or service not known
> [Errno -2] Name or service not known
> [Errno -2] Name or service not known
> [Errno 22] Invalid argument
> encoding with 'idna' codec failed (UnicodeError: label empty or too long)
> [Errno -2] Name or service not known
> Could not contact NTP servers after 6 retries

**Comment by cyyber** [comment]
Can you please provide more details of your ntp server? Which NTP Server are you using? Whats your OS?

**Comment by kprimice** [comment]
It is a private ntp server. If I don't use a custom config file I get:

> No response received from pool.ntp.org.
> No response received from ntp.ubuntu.com.

Then if I try to use my private ntp server, or pool.ntp.org/ntp.ubuntu.com in a custom config file I get the same output:

> [Errno -2] Name or service not known
> [Errno -2] Name or service not known
> [Errno -2] Name or service not known
> [Errno 22] Invalid argument
> encoding with 'idna' codec failed (UnicodeError: label empty or too long)
> [Errno -2] Name or service not known
> Could not contact NTP servers after 6 retries

I am running the node inside a Docker container running ubuntu 16.04

**Comment by cyyber** [comment]
Something must be blocking your internet connection. Please check if your network is working fine inside docker.

**Comment by kprimice** [comment]
The network seems to work. When I `ntpdate -q my.ntp.org` I get:

> server 138.196.194.10, stratum 3, offset -101.200448, delay 0.02609
>  1 Apr 20:16:23 ntpdate[14]: step time server 138.196.194.10 offset -101.200448 sec

**Comment by cyyber** [comment]
Are you executing the above command, inside the docker container. Or are you simply executing the command over your host machine?
Make sure you execute the above command inside the docker container, and not over your host machine.

**Comment by kprimice** [comment]
Indeed, it was executed inside the container

**Comment by cyyber** [comment]
In your above message, you said that "I updated config.yml with: ntp_servers: ntp1.myntp.com"
Please try with my.ntp.org

**Comment by kprimice** [comment]
Until now I was launching the node on a private network where there was only a private ntp available.
I just tried on a more open network where I can use the default ntp. It works without using a custom config.xml.

However I tried using a custom config.xml with the default ntp. So I just added: `ntp_servers: pool.ntp.org` and I got this:

> No response received from p.
> No response received from o.
> No response received from o.
> No response received from l.
> encoding with 'idna' codec failed (UnicodeError: label empty or too long)
> No response received from n.
> Could not contact NTP servers after 6 retries

**Comment by cyyber** [comment]
Something must be blocking your connection to the pool.ntp.org
Its working fine on our nodes. Try few servers mentioned here https://tf.nist.gov/tf-cgi/servers.cgi

**Comment by cyyber** [comment]
Can you paste here your config.yml ?

**Comment by kprimice** [comment]
Well it is working fine when I don't use a config.xml file. So I don't think it comes from my connection.
And when I use a config.yml, it is the default one provided with everything commented but one line: `ntp_servers: pool.ntp.org`
I will try a couple of other servers but I don't think it will change anything. And the error messages I get look weird, like a parsing issue:

> No response received from p.
> No response received from o.
> No response received from o.
> No response received from l.

**Comment by cyyber** [comment]
it should be like following
```
ntp_servers:
 - pool.ntp.org
```

**Comment by kprimice** [comment]
Perfect. It's working.
