### ISSUE TITLE
XMR-STAK-Nvidia results showing GPU Compute Error

### ISSUE THREAD

**Issue by epb5119** [theQRL/QRL#1172]
99% share are rejected due to "GPU Compute Error".  Any idea what the problem is?
Running XMR-STAK-Nvidia on 6xGTX1080TI rig. 
Windows 10
Pool: QRLMINING.com
threads: 32
blocks: 84
bfactor: 6
bsleep: 25
affine to cpu: false

**Comment by cyyber** [comment]
Tried with latest version of xmr-stak here https://github.com/fireice-uk/xmr-stak/releases

Make sure you choose cryptonight as the algorithm.

**Comment by jleni** [comment]
Are you overclocking your GPUs?

There have been some people in xmr-stak reporting similar problems in the past:
https://github.com/fireice-uk/xmr-stak-amd/issues/181
https://github.com/fireice-uk/xmr-stak-nvidia/issues/124

**Comment by epb5119** [comment]
Default settings on core and mem. 
Power Limit is set to 75%

Basic responses point to not using this miner and moving to XMR-STAK Unified all in One Monero miner. That gives a different error.
