### ISSUE TITLE
Decimal Limitation on TokenTransaction

### ISSUE THREAD

**Issue by cyyber** [theQRL/QRL#1198]
A condition to verify the limit of decimal limitation while creating token is required.
max decimals = 19 - log10(max amount) - 1

**Comment by jleni** [comment]
It would be a good idea to verify the formula and add positive/negative tests.
There are some disabled tests here: 
https://github.com/theQRL/QRL/blob/20700bbe1be2622e563c9c226ee7d76bdc582b31/tests/tools/test_cli.py#L734

the proto definition uses uint64t. That limits the max value to 18,446,744,073,709,551,615.
depending on the max amount defined for the token, the number of decimal positions should be restricted so all values are representable.

**Comment by cyyber** [comment]
Issue fixed in PR #1257
