### ISSUE TITLE
Wallet encryption: why is Qaddress encrypted?

### ISSUE THREAD

**Issue by randomshinichi** [theQRL/QRL#1211]
I don't want to risk being keylogged just because I need my Qaddress to copypaste somewhere.

Juan's idea:
Primary concern: keep backwards compatibility, with web/desktop wallets. add an additional field called name, which defaults to the Qaddress.

Rebuttal: users might never assign a name then because they'd lose convenience. Also, more functionality would need to be written to manage the name.

**Comment by jleni** [comment]
A version field will be added to wallet json files.
Files without a version number (<0.62.x) will be assumed to be version = 0.

Starting from version 1, the address field will be kept unencrypted.
Unit tests for each version number should be added to the code base.

The web wallet needs to be adjusted to accordingly.

**Comment by jleni** [comment]
Functionality incorporated in #1239
