### ISSUE TITLE
CLI, Wallet should be able to handle token migration era wallets in the future

### ISSUE THREAD

**Issue by randomshinichi** [theQRL/QRL#1213]
Token migration just started, we need tests to ensure that Wallet() will not throw errors while loading current wallet.json format (0.62.x).

**Comment by randomshinichi** [comment]
- [ ] wallet versioning: 0 is current format, 1 is future format with unencrypted Qaddress.
- [ ] Wallet unit test for both versions

**Comment by jleni** [comment]
Let's track this functionality in issue #1211
