### ISSUE TITLE
Node crash at startup

### ISSUE THREAD

**Issue by kprimice** [theQRL/QRL#1215]
Logs of the crash:

> 2018-04-11 05:53:25,499|0.62.4|unsynced| INFO : grpc public service - started !
> 2018-04-11 05:53:25,502|0.62.4|unsynced| INFO : grpc admin service - started !
> 2018-04-11 05:53:25,503|0.62.4|unsynced| INFO : [TWISTED] P2PFactory starting on 9000
> 2018-04-11 05:53:25,503|0.62.4|unsynced| INFO : <<<Reconnecting to peer list: {'204.12.250.162', '104.237.3.185', '34.208.138.15', '54.193.74.221', '104.251.219.40', '138.195.214.85', '149.210.161.156', '35.177.72.178', '104.251.219.145', '45.79.111.72', '35.177.60.137', '27.32.6.123', '104.251.219.215', '59.167.234.206', '91.121.87.21'}
> 2018-04-11 05:53:25,523|0.62.4|unsynced| INFO : QRL blockchain ledger 0.62.4
> 2018-04-11 05:53:25,523|0.62.4|unsynced| INFO : mining/staking address Q010600783d709c08609a10b5dc7d0a1a0eedce9178c32cc64deffc2471870bf76bed76dcc9155b
> 2018-04-11 05:53:25,536|0.62.4|unsynced| INFO : 35.177.60.137 peers data received: {'204.12.250.162', '34.208.138.15', '46.101.147.179', '138.195.214.85', '149.210.161.156', '45.79.111.72', '35.177.60.137', '72.225.162.21', '59.167.234.206', '91.121.87.21'}
> 2018-04-11 05:53:25,549|0.62.4|unsynced| INFO : 35.177.60.137 version: local-dev | genesis prev_headerhash b'Excession'
> 2018-04-11 05:53:25,838|0.62.4|unsynced| INFO : 45.79.111.72 peers data received: {'35.177.60.137', '72.225.162.21', '91.121.87.21'}
> 2018-04-11 05:53:25,839|0.62.4|unsynced| INFO : 45.79.111.72 version: 0.62.4 | genesis prev_headerhash b'Excession'
> 2018-04-11 05:53:37,005|0.62.4|unsynced| INFO : <<<Fetching block: 1 from 45.79.111.72:9000
> 2018-04-11 05:53:37,159|0.62.4|unsynced| INFO : >>> Received Block #1 9b5ca60ad54154fe80a95f062998488407649749ccd32366692866e612000300
> $

The node is running inside a docker container. Mining is turned off in the config file.

> PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
> NAME="Debian GNU/Linux"
> VERSION_ID="9"
> VERSION="9 (stretch)"
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"

> Linux 137760855af7 4.9.0-0.bpo.3-amd64 #1 SMP Debian 4.9.30-2+deb9u2~bpo8+1 (2017-06-27) x86_64 GNU/Linux

**Comment by cyyber** [comment]
Can you provide the Dockerfile here, so that we can generate the same container and look into the issue further?

**Comment by kprimice** [comment]
```
FROM debian:stretch-slim

ENV APP_USER=qrl
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt-get update \
		&& apt-get install -y --no-install-recommends \
		swig3.0 \
		python3-dev \
		python3-pip \
		build-essential \
		cmake \
		ntpdate \
		pkg-config \
		libssl-dev \
		libffi-dev \
		libhwloc-dev \
		libboost-dev && \
		apt-get clean && \
		rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip3 install -U setuptools pip
RUN pip3 install -U qrl --log /etc/pip3-qrl.log

EXPOSE 9009
EXPOSE 123/udp
```

**Comment by cyyber** [comment]
I ran the above docker file. And the container is working fine for me. Node is able to sync and I don't see any problem in it.
