### ISSUE TITLE
python tests occasionally hang and do not complete

### ISSUE THREAD

**Issue by som-dev** [theQRL/QRL#1230]
I was running the QRL master branch python tests and on one occasion it locked up and couldn't finish.  I then decided to run the tests in a loop and I found that within minutes of continuous running, the tests will hang and make no further progress.  Sometimes it happens immediately and sometimes it takes awhile.  Thinking there was a problem with parallel tests, I changed pytest.ini from -n 8 to -n 1 but the tests will still freeze.

I have reproduced this a few times and the last-reported test name changes each time so I do not believe it is specific to a single test case.

**Comment by jleni** [comment]
Thanks! I will investigate this

**Comment by jleni** [comment]
We are still investigating. Some thread leaking is documented here. PR #1233 
We will add one more job for pytest repeated tests to see if we can reproduce it in CI.

**Comment by randomshinichi** [comment]
https://github.com/theQRL/QRL/pull/1243
https://github.com/theQRL/QRL/pull/1256

These should have fixed the problem.

**Comment by jleni** [comment]
Is this fixed or there are still occurrences?

**Comment by som-dev** [comment]
Unfortunately I will not have development access for a week. If someone can
run the tests in a loop for an hour that should cover it, otherwise I can
retest next week.

**Comment by jleni** [comment]
@som-dev Thanks for you answer. I will setup something to let them run continuously for an hour.

**Comment by jleni** [comment]
Ran the tests continuously for 6 hours

```
while [[ 0 -ne 1 ]]; do python setup.py test;   sleep 2; done
```

Closing for now, feel free to reopen if there this is still reproducible
.
