### ISSUE TITLE
Node stuck around block_height 12000-13000

### ISSUE THREAD

**Issue by pollodigomma** [theQRL/QRL#1231]
The node (v0.62.4) believes to be synced and keeps looping within block heights 12000-13000 (approximately). I tried once to delete ~/.qrl/data and restart the node but it got back to the same state (and at around the same heights).

eg.:
```
qrl@vmix:~$ qrl state
info {
  version: "0.62.4"
  state: SYNCED
  num_connections: 1
  num_known_peers: 22
  uptime: 34632
  block_height: 12555
  network_id: "Excession"
}
```
some minutes later...
```
qrl@vmix:~$ qrl state
info {
  version: "0.62.4"
  state: SYNCED
  num_connections: 1
  num_known_peers: 22
  uptime: 35227
  block_height: 12323
  network_id: "Excession"
}
```

**Comment by cyyber** [comment]
Please share qrl.log

**Comment by pollodigomma** [comment]
Last 25000 lines:
[qrl.last.log](https://github.com/theQRL/QRL/files/1923504/qrl.last.log)

**Comment by cyyber** [comment]
Looked to the logs, your node is maintaining cache, and we had lots of spam transactions between blocknumber 12,000 to 13,000 and so its taking time to make the cache. The state mechanism has been improved and will be available in next HF. For now you can keep running the node, it will get itself synced, but will take time.
