### ISSUE TITLE
CLI unit tests are leaking threads

### ISSUE THREAD

**Issue by jleni** [theQRL/QRL#1240]
The unit tests seem to be leaking resources.

PR #1233 shows how to enable leak detection and reproduce the problem.

We would like to apply a fix to PR #1233 and solve any leaking issues in those tests.

**Comment by randomshinichi** [comment]
Seems to be an issue with gRPC CleanupThreads, used by Channels.
gRPC docs make no mention of having to cleanup after channels.
Channel has no close() function. `del stub, del channel` doesn't work either.
