### ISSUE TITLE
Transactions - signed blobs are only hashed with sha2_256

### ISSUE THREAD

**Issue by jleni** [theQRL/QRL#1293]
Transactions before being signed are hashed with SHA2_256. 
Descriptor's hash function is not considered or applied.

**Comment by jleni** [comment]
Relabeling after internal discussions

**Comment by surg0r** [comment]
What is the status of this?

**Comment by cyyber** [comment]
We had a discussion on this with @jleni and he had discussion with Leon and it doesnt make much difference at the transaction end what hashing type do we use to calculate transaction hash, as long as the signature scheme is using the hash based on descriptor.
