### ISSUE TITLE
Larger extra nonce

### ISSUE THREAD

**Issue by seanlis** [theQRL/QRL#1322]
Some pool codebase may require a larger extra nonce.
For example, [nodejs-pool](https://github.com/Snipa22/nodejs-pool/blob/4853b1b98338c2f5a1934fab5c446f38777e1318/lib/coins/xmr.js#L119) requests blocktemplate with a 'reserve_size' of [17 bytes](https://github.com/Snipa22/nodejs-pool/blob/4853b1b98338c2f5a1934fab5c446f38777e1318/lib/coins/xmr.js#L80) to accommodate the nonce for it's  [xmr-node-proxy](https://github.com/Snipa22/xmr-node-proxy).

QRL is using a fixed 8 byte, so I have to turn off this feature in my [pool](https://qrlpool.org) temporarily.

Do you have plan to support more extra nonce bytes in the future?
Is there any reason not to put extra nonce into base transaction?

**Comment by cyyber** [comment]
Thank you for raising the issue. We will discuss with our team and will explore the further possibilities.

**Comment by cyyber** [comment]
reserve_size has already been increased to 17 bytes.
