### ISSUE TITLE
Pyqryptonight wheel fails to build

### ISSUE THREAD

**Issue by manoynmonic** [theQRL/QRL#1330]
Python 3.5 on Debian Stretch x86 machine.  Trying just to install from pip, but it always fails at building the pyqryptonight wheel, and of course fails to install pyqryptonight after that.  Other wheels build fine.

**Comment by manoynmonic** [comment]
Dang.  It's not you, it's me.  Old cpu.
$cpuid | grep -i aes
AES instruction                         = false

**Comment by eor68k** [comment]
Same issue but running an Intel J3355 Processor (2.5 GHz, Dual-Core) with AES-NI enabled. 

Confirmed AES instruction = true
