### ISSUE TITLE
Retrieval of non-existent block with API responds with found=true

### ISSUE THREAD

**Issue by som-dev** [theQRL/QRL#1335]
Minor issue.  Using version 0.63.0 and experimenting with the API I noticed if I request a block that does not exist, the API does not return anything but still reports found as true.
```
./qrl-query.py --block 14444444
INFO:root:Connected to 127.0.0.1:9009
INFO:root:response:{
  "found": true
}
```

**Comment by cyyber** [comment]
Fixed in PR #1336 
Fix will be available on next release.
