### ISSUE TITLE
Wallet not showing the correct amount of Quanta

### ISSUE THREAD

**Issue by Ompanime** [theQRL/QRL#1348]
Looking up my address (Q0106001a5feb3ca2aa716eaa4667e8e5c1d6b34fe5917bbdd2843cff1c601f1fb06d903611dee8) on the blockchain reveals that I have 17,539 Quanta (which is the correct amount). Although, when I open my wallet, it shows that my balance of Quanta is only 7,520. I tried sending 20 Quanta (with a n additional fee of 1 Quanta) to a different address to see if the balance displayed in my wallet would change/update, but it didn't.

I don't know what could be the problem.

**Comment by scottdonaldau** [comment]
Hey there @Ompanime It appears the primary wallet node has been stuck for some time, and is not in sync with the chain. We'll get this fixed up ASAP.

The primary wallet node is: 35.177.60.137

You can see on the explorer its block height is somewhat behind, which would explain this issue.

https://explorer.theqrl.org/peers

I'll release and update to the wallet momentarily to change the primary node, which will reflect your balance correctly. We'll also implement similar functionality used in explorer to determine quorum between multiple nodes and select those in sync with the chain.

**Comment by scottdonaldau** [comment]
Hey @Ompanime 

Can you please refresh the wallet website and try again? Make sure you've selected Testnet Node 1 at the top right.

Cheers,
Scott

**Comment by Ompanime** [comment]
Hey Scott, I did what you said and the balance displayed in my wallet is now correct, and matches what is shown on the block explorer! Thank you!

**Comment by scottdonaldau** [comment]
Good to hear - we'll make sure the operational work we do behind the scenes prevents this in future :)
