### ISSUE TITLE
P2PPeerManager does not check for empty peer list in correct fashion

### ISSUE THREAD

**Issue by randomshinichi** [theQRL/QRL#1390]
handle_peer_list() has this line:
`if message.plData.peer_ips is None`
which fails to do its job when message.plData.peer_ips = []

It should be
`if not message.plData.peer_ips`

Covered in test_p2ppeermanager.test_handle_peer_list_empty_peer_list_message()

**Comment by cyyber** [comment]
Fixed in PR #1398
