### ISSUE TITLE
Nodes Get Stuck while adding blocks

### ISSUE THREAD

**Issue by cyyber** [theQRL/QRL#1418]
Nodes Get stuck while adding blocks and calling to mine next block. Need to look further into the issue.

**Comment by jleni** [comment]
Many changes and fixes related to this issue are contained in PR https://github.com/theQRL/QRL/pull/1451
In particular, race conditions, etc. It is likely that this issue has been fixed.
I will keep this open in case there are new instances. We will close the issue in 2 weeks from this date if no new instances are detected.

**Comment by jleni** [comment]
The following PRs also solved other deadlock instances:
https://github.com/theQRL/QRL/pull/1505
https://github.com/theQRL/QRL/pull/1502
https://github.com/theQRL/QRL/pull/1472
