### ISSUE TITLE
Addition of --testnet flag when starting QRL node.

### ISSUE THREAD

**Issue by scottdonaldau** [theQRL/QRL#1541]
Currently the only way to join another QRL network is by defining a custom peer_list, genesis_prev_headerhash, genesis_timestamp and genesis_difficulty in your config.yml, and also providing a valid genesis.yml file.

This in turn makes joining the public QRL testnet difficult.

**Describe the solution you'd like**
The ability to start a node using a flag such as `start_qrl --testnet`, and have all of the above configuration automatically applied to your node. Potentially the state files for this chain could be stored in a separate location, so that if a user later on decided to run `start_qrl`, it won't attempt to join mainnet network using local testnet state.

As we grow, the ability for multiple testnets would be advantageous, such as for PoW and PoS chains when we are testing PoS in a public testnet. Ensure this functionality allows simple additional of multiple networks a user can flag when starting a node.

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by cyyber** [comment]
The argument --network-type has been added to switch between mainnet and testnet in PR #1644
