### ISSUE TITLE
Replace functools.lru_cache by a thread safe lru_cache

### ISSUE THREAD

**Issue by cyyber** [theQRL/QRL#1542]
functools.lru_cache is not thread safe. It has been used into several places to maintain the cache and thus should be replaced by some thread safe caching.

**Comment by simoncos** [comment]
could try cachetools: https://cachetools.readthedocs.io/en/latest/

**Comment by som-dev** [comment]
The code for functools.lru_cache (at https://github.com/python/cpython/blob/3.6/Lib/functools.py#L470) notes that "The internals of the lru_cache are encapsulated for thread safety".

**Comment by nustart0720** [comment]
> functools.lru_cache is not thread safe. It has been used into several places to maintain the cache and thus should be replaced by some thread safe caching.

It seems that functools.lru_cache is thread-safe. I agree with `som-dev `.

**Comment by hohoangtung** [comment]
```
    with lock:
        # ...        
    result = user_function(*args, **kwds)
```

That means lock just supports for lru_cache itself, not supports for user function

**Comment by 1st** [comment]
> ```
>     with lock:
>         # ...        
>     result = user_function(*args, **kwds)
> ```
> That means lock just supports for lru_cache itself, not supports for user function

Totally right. It doesn't work like a singleton, but allows the same function to be called for a few times, in a different threads if they started around the same time. Lock is not over the actual function call.
