### ISSUE TITLE
slow sync

### ISSUE THREAD

**Issue by seanlis** [theQRL/QRL#1557]
**Describe the bug**
It took me 2 days to sync a node, and it's still not finished.

**To Reproduce**
1. `start_qrl`

**Expected behavior**
faster sync

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04.1

**Additional context**
When the blockchain grows, It will probably take even more time to sync.

**Comment by cyyber** [comment]
Optimization has been done for the node syncing, as the syncing nodes will not check for any stale transaction and will not receive any new transaction. PR #1562

**Comment by seanlis** [comment]
Great. Thanks for the fast fix.
