### ISSUE TITLE
qrl_measure/measure.py input must be more than 42 bytes

### ISSUE THREAD

**Issue by cyyber** [theQRL/QRL#1566]
qrl_measure/measure.py has been created to check the hash rate of CPU. But the input bytes is of 5 bytes, while the needed input bytes must be greater than 42 bytes for this to work.

**Comment by jleni** [comment]
This is related to a fix upstream (qryptonight) where additional checks were introduced.

Extend this to >42 bytes
https://github.com/theQRL/QRL/blob/4bf6b3c1653a47a2902fca0c1e509ace098daf0a/src/qrl/measure.py#L15

The data is not important. Any values could work.

**Comment by cyyber** [comment]
Fixed in #1571
