### ISSUE TITLE
git link is incorrect of https://docs.theqrl.org/mining/pool/

### ISSUE THREAD

**Issue by darcymei** [theQRL/QRL#1569]
Hi Guys,

I find pool git link of https://docs.theqrl.org/mining/pool/ is incorrect(pls check the pic). It still points to https://docs.theqrl.org/mining/pool/ instead of a github address. Can any one tell me which fork of zone117x node-cryptonote-pool should be used? Many thanks.
![1](https://user-images.githubusercontent.com/34210743/44450767-50d57500-a624-11e8-8efb-da86e8f6e6e2.png)

**Comment by darcymei** [comment]
no one reply, just close it~~

**Comment by cyyber** [comment]
@jackalyst (Jack) and @fr1t2 (James) can you take a look to this

**Comment by fr1t2** [comment]
Fix in the works, awaiting approval. Thanks for pointing this out @darcymei and sorry for the broken link!
