### ISSUE TITLE
[Question] How to sign/verify messages like Bitcoin?

### ISSUE THREAD

**Issue by danimesq** [theQRL/QRL#1589]

**Comment by danimesq** [comment]
Reference: https://github.com/HelloZeroNet/ZeroNet/issues/1686

**Comment by surg0r** [comment]
We can add this functionality. 

However, signing arbitrary data is not recommended from a QRL `XMSS` address as the signature scheme is stateful, which raises the potential risk of one-time signature re-use.

A solution maybe to create a message transaction in the webwallet and incorporate the data to be signed into the `message_tx` field. In this way the signature usage is recorded safely and may be accessed easily through a blockchain lookup. 

Another thought could be to reserve a series of one-time signature positions specifically not for fund transfer - such as signing etc.

Finally, re-using a one-time signature that has been used on chain is also a possibility as this will not risk funds in the account, but this opens up the theoretical possibility of a brute force attack from a powerful adversary to forge another signature from that position (although non-trivial) and is therefore not recommended by the project.

**Comment by danimesq** [comment]
@surg0r 

ZeroNet uses Bitcoin addresses for user identies, and they sign data to post using their privatekey.
Sites occur at the same form: files are signed with site address and visitors verifies if the files comes from the site.

What is the best fit of QRL for ZeroNet?

@HelloZeroNet @shortcutme
