### ISSUE TITLE
[Question] How to generate address on Python API?

### ISSUE THREAD

**Issue by danimesq** [theQRL/QRL#1590]

**Comment by cyyber** [comment]
Take a look to https://api.theqrl.org/#qrl-api

**Comment by danimesq** [comment]
Yes, I know this link. Thanks
But I'm asking because I didn't found it

**Comment by danimesq** [comment]
Reference: https://github.com/HelloZeroNet/ZeroNet/issues/1686

**Comment by cyyber** [comment]
> Yes, I know this link. Thanks
> But I'm asking because I didn't found it

You may use wallet daemon if it makes sense to your use case. 
https://api.theqrl.org/?python#addnewaddress
Wallet daemon has been created for use cases like exchanges.

Or you may also use CLI to addnewaddress
https://docs.theqrl.org/wallet/wallet-cli/

**Comment by danimesq** [comment]
@HelloZeroNet @shortcutme @tangdou1
Do you consider implementing it as default on the current user cert plugins?

**Comment by surg0r** [comment]
Let us know if you need any more help guys

**Comment by cyyber** [comment]
You may contact our devs directly on our official discord channel https://discord.gg/jBT6BEp
