### ISSUE TITLE
qrl_grpc_proxy - "code": -32000, "message": "Server error"

### ISSUE THREAD

**Issue by peipeitu** [theQRL/QRL#1612]
Start qrl_grpc_proxy and try to use the rpc, but the result is always error.
curl -X POST http://127.0.0.1:18090/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"getlastblockheader"}' -H 'Content-Type: application/json'
{"error": {"code": -32000, "message": "Server error", "data": {"type": "_Rendezvous", "args": [], "message": "<_Rendezvous of RPC that terminated with (StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded)>"}}, "id": "0", "jsonrpc": "2.0"}

I didn't change any default configration.
Can anyone tell my the reason and how to fix it?
Thanks a lot!

**Comment by cyyber** [comment]
Please ensure you have followed the instructions mentioned on this documentation https://docs.theqrl.org/mining/pool/
