### ISSUE TITLE
QRL 1.1.11 does not start with Illegal Instruction, older CPU suspected

### ISSUE THREAD

**Issue by useribs** [theQRL/QRL#1614]
**Describe the bug**

root@4658a0818a04:/# start_qrl
Illegal instruction (core dumped)

core file: https://file.io/1SIUCz

**To Reproduce**
1. start_qrl

**Expected behavior**

QRL starts

**Desktop (please complete the following information):**

ubuntu-docker under CentOS  3.10.0-957.5.1.el7.x86_64

**Comment by useribs** [comment]
[cpuinfo.txt](https://github.com/theQRL/QRL/files/2931285/cpuinfo.txt)

**Comment by cyyber** [comment]
Host OS - CentOS 3.10.0-957.5.1.el7.x86_64

Docker Container's Details on which QRL crashed
OS - 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

gcc (Ubuntu 5.4.0-6ubuntu1-16.04.10) 5.4.0 20160609
g++ (Ubuntu 5.4.0-6ubuntu1-16.04.10) 5.4.0 20160609

Python 3.5.2

uname -i
x86_64

**Comment by cyyber** [comment]
avx2 instructions found in keccak library, which is being used by QRL for hashing purposes. User's hardware doesn't support avx2 instructions.

**Comment by useribs** [comment]
May i propose to mention this info, together win AES-NI, as a prereq on https://docs.theqrl.org/node/QRLnode/ ?

**Comment by fr1t2** [comment]
Will add and update the documentation to include this requirement.

**Comment by useribs** [comment]
@fr1t2 awesome. Tho i think avx2 are not really necessarry, it's just enabled by default during build process. Folks here claim it has little impact: 
https://www.reddit.com/r/MoneroMining/comments/6qdr8a/notes_on_building_running_xmrstack_and_cpu_pinning/dl080tj
