### ISSUE TITLE
Website landing page dropdown menus

### ISSUE THREAD

**Issue by PQAdvantage** [theQRL/QRL#1616]
1) **About**  
  --> What is QRL?
  --> FAQ
  --> Team
  --> Roadmap
  --> Whitepapers
  --> In the Press
  --> QRL Foundation
2)  **Get Started**
  --> Buy & Sell QRL (link to Bittrex)
  --> Wallets (link to web wallet etc.)
  --> Mining (link to quick start guide)
  --> Nodes (link to guide)
3) **Community** 
  --> Discord
  --> Medium
  --> Reddit
  --> Twitter
  --> Facebook 
  --> Conferences
4) **Developers** --> keep the same dropdowns
5) **Security** 
  --> Audits (link to info about audits) 
  --> Cryptography (link to info about XMSS etc)
  --> Consensus Mechanism (link to info about current/QIP)
6) **Updates**  
  --> Announcements (links to latest Medium post)
 --> QRL Improvement Proposals (QIPs)
7) **Resources** 
 --> Explorer
  --> Github
  --> NIST (link to https://csrc.nist.gov/)
  --> Quantum Computing Report (link to https://quantumcomputingreport.com/)
  --> Anything else?
8) **Contact Us** 
 --> General
 --> Media
  -->Partners
  --> Exchanges
  --> Support

**Comment by doctor-gonzo** [comment]
Really nice collection of things that should be linked to, if there is not enough physical room on the top of the website for this I think it would make sense to have

- **Contact Us** in the footer
- **Community** and potentially **Security** rolled into *About* somehow
 
I also think wallet / explorer should be near each other, I liked how it used to be a corner menu item. Thanks for putting in the time to write this @PQAdvantage. There definitely should be a link to an exchange and a link to a comprehensive page for potential partners

**Comment by PQAdvantage** [comment]
Thanks, I concur re concerns about space.  I should add I like the links for 'Academia' that were added, but I think maybe they should be rolled into a broader dropdown.  Also, I think potential partners is so important that it may make sense for 'Partners' to be a top level drop down with links to contact email, comprehensive page with info about QRL, anything else that would be potentially attractive.

**Comment by jplomas** [comment]
Chaps these are great points for the website maintainers but this is the QRL node repo: could you please direct the discussion to https://github.com/theQRL/theqrl.org/issues ?

Thanks!
