### ISSUE TITLE
Node can become unresponsive calling GetTokenTxn()

### ISSUE THREAD

**Issue by som-dev** [theQRL/QRL#1630]
Running the qrl node from the dev branch and the testnet.  Made a call to the GRPC GetTokenTxn() method with TokenTxnReq.decimals set to a very large number and the node becomes unresponsive.
The thread is stuck at src/qrl/core/txs/TokenTransaction.py: allowed_decimals = self.calc_allowed_decimals(sum_of_initial_balances // 10 ** self.decimals)
trying to calculate a very large 10^decimals number.
There was no token creation, this was a TokenTxnReq that had junk values for each field.

**Comment by cyyber** [comment]
Issue fixed in #1632 

Thanks!!

**Comment by som-dev** [comment]
Pulled the update in dev and the node no longer gets stuck so looks good to me!  Thanks.
