### ISSUE TITLE
GetOTS with large page_count can cause unresponsive node

### ISSUE THREAD

**Issue by som-dev** [theQRL/QRL#1666]
Running new testnet qrl 0.2.0 on a virtual machine (VirtualBox).  Node appeared synced with testnet.

Called Public API GetOTS with very large page_count parameter 1073741823.

My entire VM became unresponsive, had to close it down.  Seems like large memory usage was to blame.  Perhaps a large page_count can result in a runaway process and checking for reasonable parameters is appropriate here?

Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Comment by cyyber** [comment]
Thanks for reporting. Issue has been fixed in PR #1670 
Fix will be available on next release.
