### ISSUE TITLE
start_qrl core dumps

### ISSUE THREAD

**Issue by pibara** [theQRL/QRL#1717]
**Describe the bug**
When running start_qrl with the option --qrldir, the command eventually core dumps. When restarted is core dumps promptly.

**Expected behavior**
Something else than a coredump

**Screenshots**
Added a bit of code to start_qrl to make it use faulthandler

```python
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
import faulthandler
from qrl.main import main
if __name__ == '__main__':
    faulthandler.enable()
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

The result:

![image](https://user-images.githubusercontent.com/289546/103402416-5aa10880-4b4d-11eb-9d0e-48d05f8566bc.png)

When running with logging set to DEBUG, the last logged info is:

![image](https://user-images.githubusercontent.com/289546/103402895-87a1eb00-4b4e-11eb-9733-d22dde8880d5.png)

**Desktop:**
 - OS: Ubuntu 18.04

**Comment by cyyber** [comment]
Please check your available disk space for /export/home/rob/qrl

**Comment by pibara** [comment]
> Please check your available disk space for /export/home/rob/qrl

![image](https://user-images.githubusercontent.com/289546/103403443-617d4a80-4b50-11eb-830b-0510bd9941b0.png)

**Comment by cyyber** [comment]
Does your CPU support aes-ni ?
Check via following command if it gives you any output
cat /proc/cpuinfo | grep aes

**Comment by pibara** [comment]
![image](https://user-images.githubusercontent.com/289546/103411084-7bc62100-4b6e-11eb-9b76-16869930f601.png)

**Comment by cyyber** [comment]
Please provide output of following commands

`lsb_release -a`

`free`

`cmake --version`

`gcc --version`

`g++ --version`

`python3 --version`

**Comment by pibara** [comment]
![image](https://user-images.githubusercontent.com/289546/103524368-c05b0080-4e7d-11eb-9cc4-87a8be4c68be.png)

**Comment by cyyber** [comment]
We tried to setup the node with same environment as mentioned above (with 2 GB RAM) and we are not able to repeat the above issue. I think this is something more related to your environment or hardware. This issue may also happen if for some reason the filesystem is broken.
I will suggest you to setup a fresh node.
