### ISSUE TITLE
QRL CLI fails to install on Fedora 33 - hardcoded dependency protobuf-3.12.0 is no longer available.

### ISSUE THREAD

**Issue by qtlin** [theQRL/QRL#1718]
**Describe the bug**
QRL CLI fails to install on Fedora 33 because hardcoded dependency protobuf-3.12.0 is no longer available.

**To Reproduce**
$ pip install --upgrade --user qrl
...
ERROR: Could not find a version that satisfies the requirement protobuf==3.12.0 (from qrl) (from versions: 2.0.0b0, 2.0.3, 2.3.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, 3.0.0a2, 3.0.0a3, 3.0.0b1, 3.0.0b1.post1, 3.0.0b1.post2, 3.0.0b2, 3.0.0b2.post1, 3.0.0b2.post2, 3.0.0b3, 3.0.0b4, 3.0.0, 3.1.0, 3.1.0.post1, 3.2.0rc1, 3.2.0rc1.post1, 3.2.0rc2, 3.2.0, 3.3.0, 3.4.0, 3.5.0.post1, 3.5.1, 3.5.2, 3.5.2.post1, 3.6.0, 3.6.1, 3.7.0rc2, 3.7.0rc3, 3.7.0, 3.7.1, 3.8.0rc1, 3.8.0, 3.9.0rc1, 3.9.0, 3.9.1, 3.9.2, 3.10.0rc1, 3.10.0, 3.11.0rc1, 3.11.0rc2, 3.11.0, 3.11.1, 3.11.2, 3.11.3, 3.12.2, 3.12.4, 3.13.0rc3, 3.13.0, 3.14.0rc1, 3.14.0rc2, 3.14.0rc3, 3.14.0, 4.0.0rc1, 4.0.0rc2)
**_ERROR: No matching distribution found for protobuf==3.12.0 (from qrl)_**

**Desktop (please complete the following information):**
Fedora 33 latest

**Additional context**
From https://docs.theqrl.org/node/QRLnode/#redhatfedora

**Comment by cyyber** [comment]
We will look into for the fix for Fedora 33. However this will take sometime, in the meantime you can still run QRL on Ubuntu 18.xx, 19.xx without any issue as they are well tested.

**Comment by qtlin** [comment]
Unfortunately I don't have acces to Ubuntu. Is there a strong reason to use exact version requirement?
https://github.com/theQRL/QRL/blob/master/requirements.txt lists `protobuf==3.12.0`. I would like to try to change it locally to protobuf==3.12.2 and install from a local copy. I recall pip can be pointed to a folder with sources. Could anyone remind the syntax? Thank you.

**Comment by cyyber** [comment]
If you want to build locally. You may clone the repo 

1> 
git clone https://github.com/theQRL/QRL ~/QRL

2> Then you may change requirements.txt having line
protobuf==3.12.2

3> 
pip3 install -r ~/QRL/requirements.txt

4> 
export PYTHONPATH=~/QRL/src

5> 
cd ~/QRL/

6> 
python3 start_qrl.py

**Comment by cyyber** [comment]
protobuf has been upgraded to 3.15.8
