### ISSUE TITLE
QRL cannot be installed on Raspberry Pi 4B

### ISSUE THREAD

**Issue by DevelopDaily** [theQRL/QRL#1732]
The QRL installation will fail because the `pyqryptonight `and `pyqrandomx `cannot be installed on Ubuntu 20.04 Server running on Raspberry Pi 4B.

The Raspberry Pi may not be powerful enough to earn any coins, but it is very good for development and testing. Would you please make the QRL work for the Pi?

The same installation procedure on Ubuntu 20.04 Server with AMD CPU works perfectly.

**Comment by cyyber** [comment]
AES-NI support is required to install the above libraries. I don't think Raspberry Pi has support for AES-NI. This could be checked via following command

cat /cpu/procinfo | grep aes

If the above command doesn't give any output, then it means your hardware doesn't support AES-NI
