### ISSUE TITLE
grpc_proxy attribute error

### ISSUE THREAD

**Issue by cyizard** [theQRL/QRL#1746]
i7 4790K 16Mb Ram

Node running and synced
Wallet made
made 100 slaves
then run qrl_grpc_proxy

$ qrl_grpc_proxy
Traceback (most recent call last):
  File "/home/pool/.local/bin/qrl_grpc_proxy", line 5, in <module>
    from qrl.grpcProxy import main
  File "/home/pool/.local/lib/python3.8/site-packages/qrl/grpcProxy.py", line 17, in <module>
    from flask import Flask, Response, request
  File "/home/pool/.local/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/home/pool/.local/lib/python3.8/site-packages/flask/json/__init__.py", line 31, in <module>
    _slash_escape = "\\/" not in _json.dumps("/")
AttributeError: module 'itsdangerous.json' has no attribute 'dumps'

**Comment by cyyber** [comment]
Can you please share the following details?
- OS Name & Version
- qrl --version
- pip3 --version

**Comment by cyizard** [comment]
Hi cyyber,

thanks for your reply..

I ran this on Mint 20.3 una.  I realize the instructions are for ubuntu 18 and I can certainly switch OS and try again.  I would ultimately like to set this up as a dedicated pool server.
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
QRL Command Line Interface, version 3.0.1 python



SINCE  I got you.... The bigger issue for me right now is:

git clone https://github.com/muscleman/cryptonote-nodejs-pool.git pool   

does not work...has me sign in using username and password then fails do to "username and password no longer valid--must use tokens"

SO I use 2 factor authentication token and still no luck..

I've tried Dvandal also with no luck --- but at least lets me download, fails during npm update.

**Comment by cyyber** [comment]
The default cryptonote nodejs pool will not work. We made changes to these pool code to make it compatible with QRL node. Try this repo https://github.com/cyyber/cryptonote-nodejs-pool/#cryptonote-nodejs-pool , it already have qrl.json config https://github.com/cyyber/cryptonote-nodejs-pool/blob/master/config_examples/qrl.json

Please follow this link https://docs.theqrl.org/mining/pool/ to setup mining pool.
