### ISSUE TITLE
BlockChain download /sync is slow

### ISSUE THREAD

**Issue by tye-mustafa** [theQRL/QRL#1751]
I'm new to crypto and this sync is kind of v slow can we speed this up?
1 sec 3 clocks sync
using WSL latest windows 11
![image](https://user-images.githubusercontent.com/26303106/184504556-75741060-bc6d-4a35-8305-63f30efdad23.png)

**Comment by jplomas** [comment]
There are state files available at https://qrl.co.in/chain/ which will speed things up considerably and are provided by a trusted community member.

[Our upcoming Golang node should sync faster…]
