### ISSUE TITLE
savenewaddress allows to save the same address many times

### ISSUE THREAD

**Issue by jupiter126** [theQRL/QRL#303]
To reproduce condition:
1. use getnewaddress to generate new address
2. use savenewaddress multiple times, it will save the same one multiple times

**Comment by jleni** [comment]
This will probably change a lot in the next week so it makes sense to delay fixing. It is likely that the new implmentation will fix this.

**Comment by jleni** [comment]
Telnet interface will be soon deprecated. In the next few weeks the recommend approach is to use the webwallet. A new CLI based on grpc will be available soon.

**Comment by cyyber** [comment]
Telnet client has been replaced by command line client.
