### ISSUE TITLE
walletprotocol: 'search' when Qaddress has txns, it fails trying to cast list to bytes

### ISSUE THREAD

**Issue by randomshinichi** [theQRL/QRL#315]
Telnet: search Q871011bfa3d8fb9e41c8b59904a116c31a028bab1eadcf5711e64b3445869034d6769cab
(Genesis address with transactions)

In Chain.search_address()
```
my_txn = []
try:
    my_txn = self.state.db.get('txn_' + address)
except:
    pass

for txn_hash in my_txn:
    txn_metadata = self.state.db.get(txn_hash)
```

my_txn is a list of lists, and txn_hash is a list. However, self.state.db.get() expects something which can be cast to bytes:

```
    def get(self, key_obj):
        if not isinstance(key_obj, bytes):
            key_obj = bytes(key_obj, 'utf-8')
        value_obj = self.db.Get(key_obj)
```

So when key_obj is a list, line 3 fails.

**Comment by jleni** [comment]
Fixed in PR #345
