### ISSUE TITLE
Dependency problem: pyasn1 is not available

### ISSUE THREAD

**Issue by ghost** [theQRL/QRL#328]
**All deps seem to be installed.**

:~/QRL# pip3 install -r requirements.txt
Requirement already satisfied: jsonpickle>=0.9.5 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: leveldb>=0.19 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: statistics>=1.0.3.5 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: ntplib>=0.3.3 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: Twisted==17.5.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: colorlog>=3.0.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: simplejson>=3.11.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied: PyYAML==3.12 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied: service_identity in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied: pyopenssl>=17.3.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied: pyqrllib>=0.1.20 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied: docutils>=0.3 in /usr/local/lib/python3.5/dist-packages (from statistics>=1.0.3.5->-r requirements.txt (line 4))
Requirement already satisfied: zope.interface>=4.0.2 in /usr/local/lib/python3.5/dist-packages (from Twisted==17.5.0->-r requirements.txt (line 6))
Requirement already satisfied: constantly>=15.1 in /usr/local/lib/python3.5/dist-packages (from Twisted==17.5.0->-r requirements.txt (line 6))
Requirement already satisfied: hyperlink>=17.1.1 in /usr/local/lib/python3.5/dist-packages (from Twisted==17.5.0->-r requirements.txt (line 6))
Requirement already satisfied: Automat>=0.3.0 in /usr/local/lib/python3.5/dist-packages (from Twisted==17.5.0->-r requirements.txt (line 6))
Requirement already satisfied: incremental>=16.10.1 in /usr/local/lib/python3.5/dist-packages (from Twisted==17.5.0->-r requirements.txt (line 6))
Requirement already satisfied: pyasn1-modules in /usr/local/lib/python3.5/dist-packages (from service_identity->-r requirements.txt (line 10))
Requirement already satisfied: attrs in /usr/local/lib/python3.5/dist-packages (from service_identity->-r requirements.txt (line 10))
Requirement already satisfied: pyasn1 in /usr/lib/python3/dist-packages (from service_identity->-r requirements.txt (line 10))
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3/dist-packages (from pyopenssl>=17.3.0->-r requirements.txt (line 11))
Requirement already satisfied: cryptography>=1.9 in /usr/local/lib/python3.5/dist-packages (from pyopenssl>=17.3.0->-r requirements.txt (line 11))
Requirement already satisfied: scikit-build in /usr/local/lib/python3.5/dist-packages (from pyqrllib>=0.1.20->-r requirements.txt (line 12))
Requirement already satisfied: setuptools in /usr/local/lib/python3.5/dist-packages (from zope.interface>=4.0.2->Twisted==17.5.0->-r requirements.txt (line 6))
Requirement already satisfied: cffi>=1.7 in /usr/local/lib/python3.5/dist-packages (from cryptography>=1.9->pyopenssl>=17.3.0->-r requirements.txt (line 11))
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python3.5/dist-packages (from cryptography>=1.9->pyopenssl>=17.3.0->-r requirements.txt (line 11))
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python3.5/dist-packages (from cryptography>=1.9->pyopenssl>=17.3.0->-r requirements.txt (line 11))
Requirement already satisfied: wheel>=0.29.0 in /usr/lib/python3/dist-packages (from scikit-build->pyqrllib>=0.1.20->-r requirements.txt (line 12))
Requirement already satisfied: pycparser in /usr/local/lib/python3.5/dist-packages (from cffi>=1.7->cryptography>=1.9->pyopenssl>=17.3.0->-r requirements.txt (line 11))

**But when i start the node i get**: 

:~/QRL# python start_qrl.py
dependencies not satisfied, run [pip3 install -r requirements.txt] first.
 The 'pyqrllib>=0.1.20' distribution was not found and is required by the application

**Comment by jleni** [comment]
You are installing with `pip3` (python 3) and running with python (python 2).

use `python3 start_qrl.py` instead

python (python 2) does not find the package, because it does not exist for python 2.

I agree that we could show an error saying `Python2 is not supported` or similar

**Comment by ghost** [comment]
:~/QRL#  python3 start_qrl.py
dependencies not satisfied, run [pip3 install -r requirements.txt] first.
 (pyasn1 0.1.9 (/usr/lib/python3/dist-packages), Requirement.parse('pyasn1<0.4.0,>=0.3.4'), {'pyasn1-modules'})

**Comment by jleni** [comment]
Ok, that is different...  something is looking for pyasn1.. 
I will keep this open for investigation.

if you want to move forward, run `pip3 install pyasn1`

**Comment by jleni** [comment]
which operating system are you using?

**Comment by ghost** [comment]
root@666:~/QRL# uname -a
Linux vps143664 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

root@vps143664:~/QRL# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

root@666:~/QRL# pip3 install pyasn1
Requirement already satisfied: pyasn1 in /usr/lib/python3/dist-packages

**Comment by ghost** [comment]
Oke, so i reinstalled that pip package and node started without any problems.
Fixed.

**Comment by jleni** [comment]
Yes, you were using 0.1.9 and I locally have 0.3.6

Probably I should have asked you to upgrade.
`pip3 install -U pyasn1`
