### ISSUE TITLE
Recovery of wallet address Bug

### ISSUE THREAD

**Issue by jomarip** [theQRL/QRL#39]
After recovery of a wallet address use the hex seed or recovery words, the wallet address starts working through the keys from the initial key pair. Thus, it will not pass any transactions until all the old keys are reused. 
E.g. I used my address to send 60 transaction then started a new node. If I use the recover function I would have to attempt 60 transactions before I reach a new usable signature pair

**Comment by surg0r** [comment]
A simple fix could be to count the number of public keys in the state-db stored with the xmss address, then simply select the OTS index based upon that during recovery or if there is an error with OTS signing.

**Comment by surg0r** [comment]
We are moving to a system where the wallet OTS number can be identified from the blockchain data. This will then not be a problem going forward.
