### ISSUE TITLE
Build problems on OS X with wallet and runtime error with QRL

### ISSUE THREAD

**Issue by ericjarvies** [theQRL/QRL#455]
How exactly would you like me to report on the run time errors?  Too many of them to copy and paste here (exceptions, failed to parse this and that, etc.).

**Comment by cyyber** [comment]
You may share the qrl.log to us via discord

**Comment by cyyber** [comment]
Your log shows that you cloned from the master branch which is under development. Please clone from 0.53.1a branch using the following command.
git clone https://github.com/theQRL/QRL --branch 0.53.1a
