### ISSUE TITLE
"start_qrl" fails to launch if port 8080 is in use.

### ISSUE THREAD

**Issue by ericjarvies** [theQRL/QRL#493]
Type: Enhancement
Priority: Low

When launching QRL (**start_qrl**), if another application/service is already using port 8080, QRL fails to launch.

Instead of failing, can QRL [_automatically_] use another port instead?

**Comment by jleni** [comment]
Port 8080 will not be used anymore one we complete the migration to grpc. Nevertheless, we may need to evaluate if it is possible to move grpc 9009 dynamically to other ports.

**Comment by ubidefeo** [comment]
hey @jleni 
what's port 8080 for?
- web wallet connects over 3000
- telnet is on 2000

I can telnet to it and it gets connected (of course, being a TCP port on listen), but any character I type in gets the session ended and triggers this in the log

```python
2017-11-04 20:18:37,534 |synced| INFO : Connection lost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
```

**Comment by jleni** [comment]
Here is the summary:

2000- telnet - Will be removed soon
8080 - REST API - Will be removed soon (this was used by the old webwallet and the old block explorer)
9009 - grpc API - That is the new API. It will be the only open port one the migration is finished

webwallet is already using grpc 
blockexplorer will move to grpc soon and we will remove 8080
cli will soon move to grpc and we will remove telnet (2000)

Port 3000 is the connection between the webwallet frontend and backend. It is not related to the node in anyway. That is basically the standard port for meteor. You will typically do not need to open that port.

**Comment by jleni** [comment]
If in the next few days you still want to play with 8080, it is the obsolete REST API. You can check it with curl or any other tool that works for REST.

**Comment by ubidefeo** [comment]
I'll wait for a nice CLI :)

**Comment by jleni** [comment]
This is not applicable anymore. The node is not using port 8080 anymore.
