### ISSUE TITLE
Error thrown when opening webwallet

### ISSUE THREAD

**Issue by peternijhuis** [theQRL/QRL#497]
When opening localhost:8888 the following error occurs immediately:

> Unhandled Error
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
>     why = self.lineReceived(line)
>   File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 2013, in lineReceived
>     self.allContentReceived()
>   File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 2104, in allContentReceived
>     req.requestReceived(command, path, version)
>   File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 866, in requestReceived
>     self.process()
> --- <exception caught here> ---
>   File "/usr/local/lib/python3.4/dist-packages/twisted/web/server.py", line 195, in process
>     self.render(resrc)
>   File "/usr/local/lib/python3.4/dist-packages/twisted/web/server.py", line 255, in render
>     body = resrc.render(self)
>   File "/usr/local/lib/python3.4/dist-packages/twisted/web/resource.py", line 250, in render
>     return m(request)
>   File "/usr/local/lib/python3.4/dist-packages/qrl/webwallet.py", line 56, in render_GET
>     return bytes(json.dumps(tmp), 'utf-8')
>   File "/usr/lib/python3.4/json/__init__.py", line 230, in dumps
>     return _default_encoder.encode(obj)
>   File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
>     chunks = self.iterencode(o, _one_shot=True)
>   File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
>     return _iterencode(o, 0)
>   File "/usr/lib/python3.4/json/encoder.py", line 173, in default
>     raise TypeError(repr(o) + " is not JSON serializable")
> builtins.TypeError: b'Qfc0f60c91656555bdd5ba5ef711ed3963cfbd2b8b2103f1fb2373343bccaedf073c763e1' is not JSON serializable
> 
> 2017-10-25 22:45:13,845 |synced| CRITICAL : [TWISTED] Unhandled Error
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
>     why = self.lineReceived(line)
>   File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 2013, in lineReceived
>     self.allContentReceived()
>   File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 2104, in allContentReceived
>     req.requestReceived(command, path, version)
>   File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 866, in requestReceived
>     self.process()
> --- <exception caught here> ---
>   File "/usr/local/lib/python3.4/dist-packages/twisted/web/server.py", line 195, in process
>     self.render(resrc)
>   File "/usr/local/lib/python3.4/dist-packages/twisted/web/server.py", line 255, in render
>     body = resrc.render(self)
>   File "/usr/local/lib/python3.4/dist-packages/twisted/web/resource.py", line 250, in render
>     return m(request)
>   File "/usr/local/lib/python3.4/dist-packages/qrl/webwallet.py", line 56, in render_GET
>     return bytes(json.dumps(tmp), 'utf-8')
>   File "/usr/lib/python3.4/json/__init__.py", line 230, in dumps
>     return _default_encoder.encode(obj)
>   File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
>     chunks = self.iterencode(o, _one_shot=True)
>   File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
>     return _iterencode(o, 0)
>   File "/usr/lib/python3.4/json/encoder.py", line 173, in default
>     raise TypeError(repr(o) + " is not JSON serializable")
> builtins.TypeError: b'Qfc0f60c91656555bdd5ba5ef711ed3963cfbd2b8b2103f1fb2373343bccaedf073c763e1' is not JS

**Comment by scottdonaldau** [comment]
Hey @peternijhuis 

Thanks for raising this issue. We'll be removing the current web wallet very shortly, which will be replaced by our new portable wallet https://github.com/theQRL/qrl-wallet

Given it's slated for removal, we won't be working on a fix at this time.

We're publishing a blog post to introduce the new QRL Wallet very soon!
