### ISSUE TITLE
Raspberry Pi Stretch: update instructions. requires sudo for install

### ISSUE THREAD

**Issue by ubidefeo** [theQRL/QRL#509]
hi guys

I'm now at my second RPi 3 install because of SD failure.
Noticed this yesterday already, but today it's confirmed.

the Install command in the README should be changed to 

```bash
sudo pip3 install -U qrl
```

no sudo will fail to link `start_qrl`

u.

**Comment by jleni** [comment]
Thanks @ubidefeo. The instructions have been updated
