### ISSUE TITLE
GetObject of the PublicAPI Service fails to get transaction details

### ISSUE THREAD

**Issue by scottdonaldau** [theQRL/QRL#553]
When trying to get details of a transaction through the PublicAPI grpc service, it throws 'Invalid Address'.

My node gets the following in debug logs:
```
2017-11-12 00:34:32,793 |synced| DEBUG : [PublicAPI] GetObject
```

JS Client gets this:
```
I20171112-11:34:32.785(11)? Error:  Invalid Address
I20171112-11:34:32.905(11)? Exception while invoking method 'getTxnHash' Error: Invalid Address
I20171112-11:34:32.906(11)?     at /Users/scottdonald/repos/qrl/scottdonaldau/qrl-wallet/node_modules/grpc/src/node/src/client.js:554:15
```

Test transaction hash: bade7769d112ea6d0cf5aabc9499383e9e024b0451ae80445657831a331508b8

See qrl-wallet issue for more info: https://github.com/theQRL/qrl-wallet/issues/49

**Comment by jleni** [comment]
This should have been fixed in #554
