### ISSUE TITLE
Custom node port as alternative to TCP 9000

### ISSUE THREAD

**Issue by ubidefeo** [theQRL/QRL#632]
Hi guys.
As I've been mentioning in the #suggestions channel, please label this as "feature enhancement" or something appropriate.

I think it would be very beneficial to allow nodes to listen on ports other than TCP 9000.
This would let whomever has the expertise run multiple nodes behind the same public IP.

I personally am accustomed to running my own services for fun as well as for clients' custom applications.

Each node could broadcast IP:PORT as part of the announce information and the protocol could support connecting to different ports.

Hope you'll show some love to this one, to let initial network be backed by the ones who feel like running multiple staking nodes.

thank you for giving me the chance to share this

u.

**Comment by jleni** [comment]
Hi ubi,
Thanks! It is definitely happening. We are in the middle of moving the whole p2p to grpc and considering this is critical.

The default port for grpc is 9009 but we will provide a command line argument and a setting in the configuration file to support alternative port numbers.

Please keep sending suggestions!

**Comment by jleni** [comment]
Work in progress. Initial changes were introduced in #1170
