### ISSUE TITLE
Cannot open wallet after hard-fork / suggestions to make alpha-testing better

### ISSUE THREAD

**Issue by ubidefeo** [theQRL/QRL#642]
hi guys

as suggested by @cyyber on Discord I'm opening an issue related to this.
after the hard fork from the other day a lot of pieces have come loose in the alpha-tester workflow.

`qrlexplorer.info` has lost some functionality, but that we're now aware of, and being able to at least see blockheight is a starting point.

`wallet.qrlexplorer.info` has not allowed me to open the new wallet. on the other hand it's able to show me the old wallet's balance.

I think to be able to run alpha-testing we need to have detailed info about resets, forks and workflows.

- stop running nodes
- uninstall qrl (including special cases such as manually removing old versions)
- re-install the whole shebang
- erase the `.qrl` folder and all its content
- do not try to reuse old wallets

besides, on hard-fork, the first things to be updated should be qrlexplorer and wallet, and they should point to the correct network(s).

Only at that point you should ask us to resume alpha-testing.
without the tools we're just taking a shot in the dark and silly/clueless questions are going to be posted on Discord.

I appreciate the hard work, but help us help you, and help us help the network be successful on launch, as this is what many of us are here for :)

thank you for listening
u.

**Comment by cyyber** [comment]
Thanks @ubidefeo for the suggestions. Your points has been taken. A massive backend update is being performed, as we are moving towards gRPC. We will make sure, this doesn't repeat next time. We will make sure, on next hard fork, all nodes are being updated before we ask all alpha-testers to update their nodes.

Thanks for co-operating with us.

**Comment by jleni** [comment]
Yes, we are improving the workflow everywhere. Releasing is getting easier but we need much better coordination with other components. In particular about updating backend nodes, etc.

We will add release notes for major.minor changes. Hotfixes will be announced in the alpha-channel.
With respect to tools we need to integrate them in the release process.

@cyyber We should split this into two tickets: 
- On one hand we have the urgent issue of bringing things back to normal. 
- On the other hand we have to continue working on improving our processes.

**Comment by ubidefeo** [comment]
thank you guys.
I also see a lot of obsolete network nodes in the console output.
I think with better announcements it would be clearer to testers that old nodes are to be shut down.
maybe there's a way not to let these nodes participate in the cluster rather than cluttering traffic?
maybe not...

**Comment by jleni** [comment]
In the next releases we will have much better peer management so nodes will just avoid connecting.
we are using semantic versioning (MAJOR.MINOR/PATCH) Incompatible changes will be marked by an increase in that MAJOR version number.
MAJOR=0 is a kind of exception.. but I agree that at least we should avoid cluttering the logs
