### ISSUE TITLE
Installation on Fedora 25 within qubes. 

### ISSUE THREAD

**Issue by disqotech** [theQRL/QRL#693]
Hi - I cant seem to install QRL, I have attempted to install dependencies but this fails:

[user@software ~]$ sudo dnf -y install swit3.0 python3-dev python3-pip build-essential cmake pkg-config libssl-dev libffi-dev

Qubes OS Repository for VM (updates)            207 kB/s | 529 kB     00:02    
RPM Fusion for Fedora 23 - Free                 726 kB/s | 457 kB     00:00    
No package swit3.0 available.
No package python3-dev available.
Package python3-pip-7.1.0-1.fc23.noarch is already installed, skipping.
No package build-essential available.
No package pkg-config available.
No package libssl-dev available.
No package libffi-dev available.
Error: Unable to find a match.

Edit: Upgraded to fedora 25 per the recommendation from qubes [here](https://www.qubes-os.org/news/2017/07/29/fedora-25-upgrade/), retried above to same result.
Edit: Solved. Install on Debian instead of Fedora if running Qubes - instructions in the comments.

**Comment by jleni** [comment]
As discussed in Discord, we will aim to provide support for Fedora 25 and upwards. The expect fix for this isuee should involve a docker configuration to run unit/integration tests in fedora

**Comment by jleni** [comment]
According to the discussion in Discord, it is already possible to have QRL running in Qubes.
Would it make sense to create a PR with a short text describing the steps?

**Comment by disqotech** [comment]
In qubes, I was able to successfully install QRL by first upgrading the pre-installed Debian templateVM from Debian 8 to Debian 9. All the instructions for that are [here](https://www.qubes-os.org/doc/template/debian/upgrade-8-to-9/), and it works pretty smoothly. 

When you have a Debian 9 templateVM, make a new standalone VM from that template, increase its private storage allocation, and from a terminal, run the following commands exactly. 

sudo apt-get update
sudo apt-get install swig3.0 python3-dev python3-pip build-essential cmake pkg-config libssl-dev libffi-dev
sudo pip3 install -U setuptools pip
sudo pip3 install -U qrl
start_qrl

**Comment by calvix** [comment]
Hello, I run qrl on fedora 27 docker image and I install it with this(maybe it will help you):
https://github.com/calvix/qrl-node-docker/blob/master/Dockerfile#L3-L6
