### ISSUE TITLE
OTS Key Reuse Possible

### ISSUE THREAD

**Issue by scottdonaldau** [theQRL/QRL#719]
The network is accepting transactions that are signed with OTS Keys that do not match the OTS Key Index a transaction object.

Validation should be added so that the OTS Key Index defined in a 'transferCoins' object matches the first 4 bytes of a signature provided in 'pushTransaction'.

**Comment by surg0r** [comment]
Second major critical error is that self.pubhash is derived incorrectly from self.PK + ots_key..instead of a concatenation of hashes from self.pk.

This requires an urgent fix..

**Comment by cyyber** [comment]
Fixed in PoW version of Testnet
