### ISSUE TITLE
Segmentation fault when running update " pip3 install -U qrl"

### ISSUE THREAD

**Issue by galations522** [theQRL/QRL#755]
Segmentation fault
at the end of the update ?

 pip3 install -U qrl
Collecting qrl
Collecting pyqrllib>=0.2.9 (from qrl)
Collecting protobuf (from qrl)
  Using cached protobuf-3.5.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting six>=1.9 (from qrl)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting pyopenssl>=17.3.0 (from qrl)
  Using cached pyOpenSSL-17.5.0-py2.py3-none-any.whl
Collecting PyYAML==3.12 (from qrl)
Collecting simplejson>=3.11.1 (from qrl)
Collecting colorlog>=3.0.1 (from qrl)
  Using cached colorlog-3.1.0-py2.py3-none-any.whl
Collecting ntplib>=0.3.3 (from qrl)
Collecting service-identity (from qrl)
  Using cached service_identity-17.0.0-py2.py3-none-any.whl
Collecting Twisted>=17.5.0 (from qrl)
Collecting grpcio-tools>=1.6.3 (from qrl)
  Using cached grpcio_tools-1.8.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting click==6.7 (from qrl)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting leveldb==0.20 (from qrl)
Collecting grpcio>=1.6.3 (from qrl)
  Using cached grpcio-1.8.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting scikit-build (from pyqrllib>=0.2.9->qrl)
  Using cached scikit_build-0.6.1-py2.py3-none-any.whl
Collecting setuptools (from protobuf->qrl)
  Using cached setuptools-38.2.5-py2.py3-none-any.whl
Collecting cryptography>=2.1.4 (from pyopenssl>=17.3.0->qrl)
  Using cached cryptography-2.1.4-cp35-cp35m-manylinux1_x86_64.whl
Collecting attrs (from service-identity->qrl)
  Using cached attrs-17.3.0-py2.py3-none-any.whl
Collecting pyasn1 (from service-identity->qrl)
  Using cached pyasn1-0.4.2-py2.py3-none-any.whl
Collecting pyasn1-modules (from service-identity->qrl)
  Using cached pyasn1_modules-0.2.1-py2.py3-none-any.whl
Collecting constantly>=15.1 (from Twisted>=17.5.0->qrl)
  Using cached constantly-15.1.0-py2.py3-none-any.whl
Collecting Automat>=0.3.0 (from Twisted>=17.5.0->qrl)
  Using cached Automat-0.6.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1 (from Twisted>=17.5.0->qrl)
  Using cached hyperlink-17.3.1-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from Twisted>=17.5.0->qrl)
  Using cached incremental-17.5.0-py2.py3-none-any.whl
Collecting zope.interface>=4.0.2 (from Twisted>=17.5.0->qrl)
  Using cached zope.interface-4.4.3-cp35-cp35m-manylinux1_x86_64.whl
Collecting wheel>=0.29.0 (from scikit-build->pyqrllib>=0.2.9->qrl)
  Using cached wheel-0.30.0-py2.py3-none-any.whl
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=2.1.4->pyopenssl>=17.3.0->qrl)
  Using cached cffi-1.11.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=2.1.4->pyopenssl>=17.3.0->qrl)
  Using cached asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting idna>=2.1 (from cryptography>=2.1.4->pyopenssl>=17.3.0->qrl)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=2.1.4->pyopenssl>=17.3.0->qrl)
Installing collected packages: setuptools, wheel, scikit-build, pyqrllib, six, protobuf, pycparser, cffi, asn1crypto, idna, cryptography, pyopenssl, PyYAML, simplejson, colorlog, ntplib, attrs, pyasn1, pyasn1-modules, service-identity, constantly, Automat, hyperlink, incremental, zope.interface, Twisted, grpcio, grpcio-tools, click, leveldb, qrl
Segmentation fault

**Comment by cyyber** [comment]
Can you please reboot your node and try installing after that?

**Comment by galations522** [comment]
Rebooted system segmentation fault exist as user but not as sudo or root. The client runs either way the same mines and fails to transfer coins to the accounts involved. If two different problems check into seg problem first it seems it would be a more global problem. I am using debian 9 which is still unsupported

**Comment by galations522** [comment]
Know getting the following while client is running
2017-12-25 19:09:26,183|0.58.3|synced| CRITICAL : [TWISTED] Unhandled Error
Traceback (most recent call last):
  File "/home/bible1/.local/lib/python3.5/site-packages/qrl/main.py", line 127, in main
    start_legacy_services(buffered_chain, qrlnode, sync_state)
  File "/home/bible1/.local/lib/python3.5/site-packages/qrl/main.py", line 84, in start_legacy_services
    reactor.run()
  File "/home/bible1/.local/lib/python3.5/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/home/bible1/.local/lib/python3.5/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/home/bible1/.local/lib/python3.5/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/bible1/.local/lib/python3.5/site-packages/qrl/core/node.py", line 505, in post_block_logic
    self.create_next_block(blocknumber, activation_blocknumber)
  File "/home/bible1/.local/lib/python3.5/site-packages/qrl/core/node.py", line 429, in create_next_block
    hash_chain = self.buffered_chain.hash_chain_get(blocknumber)
  File "/home/bible1/.local/lib/python3.5/site-packages/qrl/core/BufferedChain.py", line 1206, in hash_chain_get
    return self.hash_chain[epoch]
builtins.KeyError: 270

**Comment by cyyber** [comment]
@galations522 I know about the KeyError issue #753 
It would be fixed soon.

You can only fail to send txn, if your wallet is in stake validator list. A stake validator is not allowed to send txn. Check your wallet list at https://explorer.theqrl.org/stakers

**Comment by jleni** [comment]
Closing this issue as it was linked to the PoS version.
Obsolete
