### ISSUE TITLE
sudo pip3 install -U qrl  Ubuntu server 14.04 old cmake + pyqrllib install error

### ISSUE THREAD

**Issue by Mrwh0** [theQRL/QRL#756]
ubuntu server 14.04

CMake Error at CMakeLists.txt:4 (cmake_minimum_required):
      CMake 3.5 or higher is required.  You are running version 2.8.12.2

  -- Configuring incomplete, errors occurred!
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3r9402om/pyqrllib/setup.py", line 70, in <module>
        setup_package()
      File "/tmp/pip-build-3r9402om/pyqrllib/setup.py", line 66, in setup_package
        use_pyscaffold=True)
      File "/usr/local/lib/python3.4/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-3r9402om/pyqrllib/.eggs/PyScaffold-2.5.8-py3.4.egg/pyscaffold/contrib/pbr/pbr/packaging.py", line 200, in run
        return du_install.install.run(self)
      File "/usr/lib/python3.4/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.4/distutils/command/build.py", line 126, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-3r9402om/pyqrllib/setup.py", line 40, in run
        subprocess.check_call(cmake_call, cwd=self.build_temp, env=env)
      File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-build-3r9402om/pyqrllib', '-DBUILD_PYTHON=ON', '-DBUILD_TESTS=OFF', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-build-3r9402om/pyqrllib/build/lib.linux-x86_64-3.4', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3r9402om/pyqrllib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-aotqwugy-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-3r9402om/pyqrllib/

**Comment by Mrwh0** [comment]
upgrading cmake wait

**Comment by jleni** [comment]
Yes, as it is explained at the beginning of the error message:

CMake 3.5 or higher is required. You are running version 2.8.12.2

**Comment by jleni** [comment]
A very recent cmake version is provided by PyPI. You can install it by running:

pip3 install -U cmake

**Comment by Mrwh0** [comment]
wget http://www.cmake.org/files/v3.5/cmake-3.5.2.tar.gz
tar xf cmake-3.5.2.tar.gz
cd cmake-3.5.2
./configure
makesudo apt-get install checkinstall
sudo checkinstall
sudo dpkg -i cmake_3.5.2-1_amd64.deb 
cmake -version
cmake version 3.5.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by Mrwh0** [comment]
sudo pip3 install -U qrl
 -- Build files have been written to: /tmp/pip-build-eo23wsdy/pyqrllib/build/temp.linux-x86_64-3.4
    [  2%] Swig source
    [  4%] Swig source
    [  6%] Swig source
    /tmp/pip-build-eo23wsdy/pyqrllib/src/dilithium/dilithium.h:7: Warning 201: Unable to find 'string'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/dilithium/dilithium.h:8: Warning 201: Unable to find 'vector'
    /tmp/pip-build-eo23wsdy/pyqrllib/deps/dilithium/ref/randombytes.h:6: Warning 201: Unable to find 'unistd.h'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/dilithium/dilithium.h:39: Warning 201: Unable to find 'vector'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/kyber/kyber.h:9: Warning 201: Unable to find 'string'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/kyber/kyber.h:10: Warning 201: Unable to find 'vector'
    /tmp/pip-build-eo23wsdy/pyqrllib/deps/kyber/ref/api.h:4: Warning 201: Unable to find 'params.h'
    /tmp/pip-build-eo23wsdy/pyqrllib/deps/kyber/ref/randombytes.h:6: Warning 201: Unable to find 'unistd.h'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/kyber/kyber.h:39: Warning 201: Unable to find 'vector'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/qrl/misc.h:7: Warning 201: Unable to find 'string'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/qrl/misc.h:8: Warning 201: Unable to find 'vector'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/qrl/misc.h:9: Warning 201: Unable to find 'stdexcept'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/qrl/hashing.h:7: Warning 201: Unable to find 'vector'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/qrl/hashing.h:8: Warning 201: Unable to find 'cstddef'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/qrl/xmss.h:6: Warning 201: Unable to find 'vector'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/qrl/xmss.h:7: Warning 201: Unable to find 'string'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/qrl/xmssBase.h:4: Warning 201: Unable to find 'string'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/qrl/xmssBase.h:5: Warning 201: Unable to find 'vector'
    /tmp/pip-build-eo23wsdy/pyqrllib/deps/xmss-alt/xmss_params.h:9: Warning 201: Unable to find 'cstdint'
    /tmp/pip-build-eo23wsdy/pyqrllib/deps/xmss-alt/wots.h:15: Warning 201: Unable to find 'cstdint'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/qrl/xmssBase.h:56: Warning 201: Unable to find 'vector'
    /tmp/pip-build-eo23wsdy/pyqrllib/deps/xmss-alt/algsxmss_fast.h:15: Warning 201: Unable to find 'cstddef'
    /tmp/pip-build-eo23wsdy/pyqrllib/deps/xmss-alt/algsxmss_fast.h:16: Warning 201: Unable to find 'wots.h'
    /tmp/pip-build-eo23wsdy/pyqrllib/deps/xmss-alt/algsxmss_fast.h:17: Warning 201: Unable to find 'xmss_common.h'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/qrl/xmssPool.h:6: Warning 201: Unable to find 'vector'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/qrl/xmssPool.h:7: Warning 201: Unable to find 'string'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/qrl/xmssPool.h:8: Warning 201: Unable to find 'future'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/qrl/xmssPool.h:9: Warning 201: Unable to find 'deque'
    /tmp/pip-build-eo23wsdy/pyqrllib/src/qrl/xmssPool.h:10: Warning 201: Unable to find 'memory'
    Scanning dependencies of target _dilithium
    Scanning dependencies of target _kyber
    [  8%] Building CXX object CMakeFiles/_dilithium.dir/src/dilithium/dilithium.cpp.o
    [ 10%] Building CXX object CMakeFiles/_dilithium.dir/build/lib.linux-x86_64-3.4/pyqrllib/dilithiumPYTHON_wrap.cxx.o
    c++: error: unrecognized command line option ‘-std=c++14’
    [ 13%] Building CXX object CMakeFiles/_kyber.dir/build/lib.linux-x86_64-3.4/pyqrllib/kyberPYTHON_wrap.cxx.o
    make[2]: *** [CMakeFiles/_dilithium.dir/src/dilithium/dilithium.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    c++: error: unrecognized command line option ‘-std=c++14’
    make[2]: *** [CMakeFiles/_dilithium.dir/build/lib.linux-x86_64-3.4/pyqrllib/dilithiumPYTHON_wrap.cxx.o] Error 1
    make[1]: *** [CMakeFiles/_dilithium.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    c++: error: unrecognized command line option ‘-std=c++14’
    make[2]: *** [CMakeFiles/_kyber.dir/build/lib.linux-x86_64-3.4/pyqrllib/kyberPYTHON_wrap.cxx.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    [ 15%] Building CXX object CMakeFiles/_kyber.dir/src/kyber/kyber.cpp.o
    [ 17%] Building CXX object CMakeFiles/_kyber.dir/deps/kyber/ref/randombytes.c.o
    c++: error: unrecognized command line option ‘-std=c++14’
    make[2]: *** [CMakeFiles/_kyber.dir/src/kyber/kyber.cpp.o] Error 1
    c++: error: unrecognized command line option ‘-std=c++14’
    make[2]: *** [CMakeFiles/_kyber.dir/deps/kyber/ref/randombytes.c.o] Error 1
    make[1]: *** [CMakeFiles/_kyber.dir/all] Error 2
    Scanning dependencies of target _pyqrllib
    [ 19%] Building CXX object CMakeFiles/_pyqrllib.dir/src/qrl/xmssPool.cpp.o
    [ 21%] Building CXX object CMakeFiles/_pyqrllib.dir/build/lib.linux-x86_64-3.4/pyqrllib/qrlPYTHON_wrap.cxx.o
    c++: error: unrecognized command line option ‘-std=c++14’
    make[2]: *** [CMakeFiles/_pyqrllib.dir/src/qrl/xmssPool.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    c++: error: unrecognized command line option ‘-std=c++14’
    make[2]: *** [CMakeFiles/_pyqrllib.dir/build/lib.linux-x86_64-3.4/pyqrllib/qrlPYTHON_wrap.cxx.o] Error 1
    [ 23%] Building CXX object CMakeFiles/_pyqrllib.dir/src/qrl/hashing.cpp.o
    [ 26%] Building CXX object CMakeFiles/_pyqrllib.dir/src/qrl/xmss.cpp.o
    c++: error: unrecognized command line option ‘-std=c++14’
    make[2]: *** [CMakeFiles/_pyqrllib.dir/src/qrl/xmss.cpp.o] Error 1
    c++: error: unrecognized command line option ‘-std=c++14’
    make[2]: *** [CMakeFiles/_pyqrllib.dir/src/qrl/hashing.cpp.o] Error 1
    make[1]: *** [CMakeFiles/_pyqrllib.dir/all] Error 2
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-eo23wsdy/pyqrllib/setup.py", line 70, in <module>
        setup_package()
      File "/tmp/pip-build-eo23wsdy/pyqrllib/setup.py", line 66, in setup_package
        use_pyscaffold=True)
      File "/usr/local/lib/python3.4/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-eo23wsdy/pyqrllib/.eggs/PyScaffold-2.5.8-py3.4.egg/pyscaffold/contrib/pbr/pbr/packaging.py", line 200, in run
        return du_install.install.run(self)
      File "/usr/lib/python3.4/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.4/distutils/command/build.py", line 126, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-eo23wsdy/pyqrllib/setup.py", line 43, in run
        '--config', 'Release', '--', '-j4'], cwd=self.build_temp)
      File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-eo23wsdy/pyqrllib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u8nwboms-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-eo23wsdy/pyqrllib/

**Comment by Mrwh0** [comment]
sudo pip3 install pyqrllib
The directory '/home/analiser/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/analiser/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyqrllib
  Downloading pyqrllib-0.3.5.tar.gz (206kB)
    100% |████████████████████████████████| 215kB 954kB/s 
Requirement already satisfied: scikit-build in /usr/local/lib/python3.4/dist-packages (from pyqrllib)
Requirement already satisfied: wheel>=0.29.0 in /usr/local/lib/python3.4/dist-packages (from scikit-build->pyqrllib)
Requirement already satisfied: setuptools>=28.0.0 in /usr/local/lib/python3.4/dist-packages (from scikit-build->pyqrllib)
Installing collected packages: pyqrllib
  Running setup.py install for pyqrllib ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xryxolzn/pyqrllib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-qetv2q17-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.4
    creating build/lib.linux-x86_64-3.4/pyqrllib
    copying pyqrllib/__init__.py -> build/lib.linux-x86_64-3.4/pyqrllib
    running egg_info
    writing pyqrllib.egg-info/PKG-INFO
    writing top-level names to pyqrllib.egg-info/top_level.txt
    writing dependency_links to pyqrllib.egg-info/dependency_links.txt
    writing requirements to pyqrllib.egg-info/requires.txt
    [pbr] Reusing existing SOURCES.txt
    running build_ext
    -- The C compiler identification is GNU 4.8.5
    -- The CXX compiler identification is GNU 4.8.5
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- BUILD_TESTS    OFF
    -- GOLANG WRAPPER OFF
    -- PYTHON WRAPPER ON
    -- WEBASSEMBLY    OFF
    -- Found SWIG: /usr/bin/swig3.0 (found version "3.0.2")
    -- Python wrapper enabled
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.3", minimum required is "3.4")
    -- CMAKE_SWIG_OUTDIR: /tmp/pip-build-xryxolzn/pyqrllib/build/lib.linux-x86_64-3.4/pyqrllib
    -- CMAKE_LIBRARY_OUTPUT_DIRECTORY: /tmp/pip-build-xryxolzn/pyqrllib/build/lib.linux-x86_64-3.4/pyqrllib
    -- CMAKE_SWIG_OUTDIR: /tmp/pip-build-xryxolzn/pyqrllib/build/lib.linux-x86_64-3.4/pyqrllib
    -- CMAKE_LIBRARY_OUTPUT_DIRECTORY: /tmp/pip-build-xryxolzn/pyqrllib/build/lib.linux-x86_64-3.4/pyqrllib
    -- CMAKE_SWIG_OUTDIR: /tmp/pip-build-xryxolzn/pyqrllib/build/lib.linux-x86_64-3.4/pyqrllib
    -- CMAKE_LIBRARY_OUTPUT_DIRECTORY: /tmp/pip-build-xryxolzn/pyqrllib/build/lib.linux-x86_64-3.4/pyqrllib
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-build-xryxolzn/pyqrllib/build/temp.linux-x86_64-3.4
    [  2%] Swig source
    [  6%] Swig source
    [  6%] Swig source
    /tmp/pip-build-xryxolzn/pyqrllib/src/dilithium/dilithium.h:7: Warning 201: Unable to find 'string'
    /tmp/pip-build-xryxolzn/pyqrllib/src/dilithium/dilithium.h:8: Warning 201: Unable to find 'vector'
    /tmp/pip-build-xryxolzn/pyqrllib/deps/dilithium/ref/randombytes.h:6: Warning 201: Unable to find 'unistd.h'
    /tmp/pip-build-xryxolzn/pyqrllib/src/dilithium/dilithium.h:39: Warning 201: Unable to find 'vector'
    /tmp/pip-build-xryxolzn/pyqrllib/src/kyber/kyber.h:9: Warning 201: Unable to find 'string'
    /tmp/pip-build-xryxolzn/pyqrllib/src/kyber/kyber.h:10: Warning 201: Unable to find 'vector'
    /tmp/pip-build-xryxolzn/pyqrllib/deps/kyber/ref/api.h:4: Warning 201: Unable to find 'params.h'
    /tmp/pip-build-xryxolzn/pyqrllib/deps/kyber/ref/randombytes.h:6: Warning 201: Unable to find 'unistd.h'
    /tmp/pip-build-xryxolzn/pyqrllib/src/kyber/kyber.h:39: Warning 201: Unable to find 'vector'
    /tmp/pip-build-xryxolzn/pyqrllib/src/qrl/misc.h:7: Warning 201: Unable to find 'string'
    /tmp/pip-build-xryxolzn/pyqrllib/src/qrl/misc.h:8: Warning 201: Unable to find 'vector'
    /tmp/pip-build-xryxolzn/pyqrllib/src/qrl/misc.h:9: Warning 201: Unable to find 'stdexcept'
    /tmp/pip-build-xryxolzn/pyqrllib/src/qrl/hashing.h:7: Warning 201: Unable to find 'vector'
    /tmp/pip-build-xryxolzn/pyqrllib/src/qrl/hashing.h:8: Warning 201: Unable to find 'cstddef'
    /tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmss.h:6: Warning 201: Unable to find 'vector'
    /tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmss.h:7: Warning 201: Unable to find 'string'
    /tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmssBase.h:4: Warning 201: Unable to find 'string'
    /tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmssBase.h:5: Warning 201: Unable to find 'vector'
    /tmp/pip-build-xryxolzn/pyqrllib/deps/xmss-alt/xmss_params.h:9: Warning 201: Unable to find 'cstdint'
    /tmp/pip-build-xryxolzn/pyqrllib/deps/xmss-alt/wots.h:15: Warning 201: Unable to find 'cstdint'
    /tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmssBase.h:56: Warning 201: Unable to find 'vector'
    /tmp/pip-build-xryxolzn/pyqrllib/deps/xmss-alt/algsxmss_fast.h:15: Warning 201: Unable to find 'cstddef'
    /tmp/pip-build-xryxolzn/pyqrllib/deps/xmss-alt/algsxmss_fast.h:16: Warning 201: Unable to find 'wots.h'
    /tmp/pip-build-xryxolzn/pyqrllib/deps/xmss-alt/algsxmss_fast.h:17: Warning 201: Unable to find 'xmss_common.h'
    /tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmssPool.h:6: Warning 201: Unable to find 'vector'
    /tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmssPool.h:7: Warning 201: Unable to find 'string'
    /tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmssPool.h:8: Warning 201: Unable to find 'future'
    /tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmssPool.h:9: Warning 201: Unable to find 'deque'
    /tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmssPool.h:10: Warning 201: Unable to find 'memory'
    Scanning dependencies of target _kyber
    [  8%] Building CXX object CMakeFiles/_kyber.dir/src/kyber/kyber.cpp.o
    [ 10%] Building CXX object CMakeFiles/_kyber.dir/build/lib.linux-x86_64-3.4/pyqrllib/kyberPYTHON_wrap.cxx.o
    c++: error: unrecognized command line option ‘-std=c++14’
    c++: error: unrecognized command line option ‘-std=c++14’
    make[2]: *** [CMakeFiles/_kyber.dir/build/lib.linux-x86_64-3.4/pyqrllib/kyberPYTHON_wrap.cxx.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    make[2]: *** [CMakeFiles/_kyber.dir/src/kyber/kyber.cpp.o] Error 1
    make[1]: *** [CMakeFiles/_kyber.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    Scanning dependencies of target _dilithium
    [ 13%] Building CXX object CMakeFiles/_dilithium.dir/build/lib.linux-x86_64-3.4/pyqrllib/dilithiumPYTHON_wrap.cxx.o
    [ 15%] Building CXX object CMakeFiles/_dilithium.dir/deps/dilithium/ref/randombytes.c.o
    c++: error: unrecognized command line option ‘-std=c++14’
    make[2]: *** [CMakeFiles/_dilithium.dir/build/lib.linux-x86_64-3.4/pyqrllib/dilithiumPYTHON_wrap.cxx.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    c++: error: unrecognized command line option ‘-std=c++14’
    make[2]: *** [CMakeFiles/_dilithium.dir/deps/dilithium/ref/randombytes.c.o] Error 1
    [ 17%] Building CXX object CMakeFiles/_dilithium.dir/src/dilithium/dilithium.cpp.o
    c++: error: unrecognized command line option ‘-std=c++14’
    make[2]: *** [CMakeFiles/_dilithium.dir/src/dilithium/dilithium.cpp.o] Error 1
    make[1]: *** [CMakeFiles/_dilithium.dir/all] Error 2
    Scanning dependencies of target _pyqrllib
    [ 19%] Building CXX object CMakeFiles/_pyqrllib.dir/src/qrl/xmss.cpp.o
    [ 21%] Building CXX object CMakeFiles/_pyqrllib.dir/build/lib.linux-x86_64-3.4/pyqrllib/qrlPYTHON_wrap.cxx.o
    [ 23%] Building CXX object CMakeFiles/_pyqrllib.dir/src/qrl/hashing.cpp.o
    [ 26%] Building CXX object CMakeFiles/_pyqrllib.dir/src/qrl/xmssPool.cpp.o
    c++: error: unrecognized command line option ‘-std=c++14’
    make[2]: *** [CMakeFiles/_pyqrllib.dir/build/lib.linux-x86_64-3.4/pyqrllib/qrlPYTHON_wrap.cxx.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    c++: error: unrecognized command line option ‘-std=c++14’
    make[2]: *** [CMakeFiles/_pyqrllib.dir/src/qrl/xmss.cpp.o] Error 1
    c++: error: unrecognized command line option ‘-std=c++14’
    make[2]: *** [CMakeFiles/_pyqrllib.dir/src/qrl/xmssPool.cpp.o] Error 1
    c++: error: unrecognized command line option ‘-std=c++14’
    make[2]: *** [CMakeFiles/_pyqrllib.dir/src/qrl/hashing.cpp.o] Error 1
    make[1]: *** [CMakeFiles/_pyqrllib.dir/all] Error 2
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xryxolzn/pyqrllib/setup.py", line 70, in <module>
        setup_package()
      File "/tmp/pip-build-xryxolzn/pyqrllib/setup.py", line 66, in setup_package
        use_pyscaffold=True)
      File "/usr/local/lib/python3.4/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-xryxolzn/pyqrllib/.eggs/PyScaffold-2.5.8-py3.4.egg/pyscaffold/contrib/pbr/pbr/packaging.py", line 200, in run
        return du_install.install.run(self)
      File "/usr/lib/python3.4/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.4/distutils/command/build.py", line 126, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-xryxolzn/pyqrllib/setup.py", line 43, in run
        '--config', 'Release', '--', '-j4'], cwd=self.build_temp)
      File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xryxolzn/pyqrllib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-qetv2q17-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-xryxolzn/pyqrllib/

**Comment by Mrwh0** [comment]
stuck here

[ 6%] Swig source
/tmp/pip-build-xryxolzn/pyqrllib/src/dilithium/dilithium.h:7: Warning 201: Unable to find 'string'
/tmp/pip-build-xryxolzn/pyqrllib/src/dilithium/dilithium.h:8: Warning 201: Unable to find 'vector'
/tmp/pip-build-xryxolzn/pyqrllib/deps/dilithium/ref/randombytes.h:6: Warning 201: Unable to find 'unistd.h'
/tmp/pip-build-xryxolzn/pyqrllib/src/dilithium/dilithium.h:39: Warning 201: Unable to find 'vector'
/tmp/pip-build-xryxolzn/pyqrllib/src/kyber/kyber.h:9: Warning 201: Unable to find 'string'
/tmp/pip-build-xryxolzn/pyqrllib/src/kyber/kyber.h:10: Warning 201: Unable to find 'vector'
/tmp/pip-build-xryxolzn/pyqrllib/deps/kyber/ref/api.h:4: Warning 201: Unable to find 'params.h'
/tmp/pip-build-xryxolzn/pyqrllib/deps/kyber/ref/randombytes.h:6: Warning 201: Unable to find 'unistd.h'
/tmp/pip-build-xryxolzn/pyqrllib/src/kyber/kyber.h:39: Warning 201: Unable to find 'vector'
/tmp/pip-build-xryxolzn/pyqrllib/src/qrl/misc.h:7: Warning 201: Unable to find 'string'
/tmp/pip-build-xryxolzn/pyqrllib/src/qrl/misc.h:8: Warning 201: Unable to find 'vector'
/tmp/pip-build-xryxolzn/pyqrllib/src/qrl/misc.h:9: Warning 201: Unable to find 'stdexcept'
/tmp/pip-build-xryxolzn/pyqrllib/src/qrl/hashing.h:7: Warning 201: Unable to find 'vector'
/tmp/pip-build-xryxolzn/pyqrllib/src/qrl/hashing.h:8: Warning 201: Unable to find 'cstddef'
/tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmss.h:6: Warning 201: Unable to find 'vector'
/tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmss.h:7: Warning 201: Unable to find 'string'
/tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmssBase.h:4: Warning 201: Unable to find 'string'
/tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmssBase.h:5: Warning 201: Unable to find 'vector'
/tmp/pip-build-xryxolzn/pyqrllib/deps/xmss-alt/xmss_params.h:9: Warning 201: Unable to find 'cstdint'
/tmp/pip-build-xryxolzn/pyqrllib/deps/xmss-alt/wots.h:15: Warning 201: Unable to find 'cstdint'
/tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmssBase.h:56: Warning 201: Unable to find 'vector'
/tmp/pip-build-xryxolzn/pyqrllib/deps/xmss-alt/algsxmss_fast.h:15: Warning 201: Unable to find 'cstddef'
/tmp/pip-build-xryxolzn/pyqrllib/deps/xmss-alt/algsxmss_fast.h:16: Warning 201: Unable to find 'wots.h'
/tmp/pip-build-xryxolzn/pyqrllib/deps/xmss-alt/algsxmss_fast.h:17: Warning 201: Unable to find 'xmss_common.h'
/tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmssPool.h:6: Warning 201: Unable to find 'vector'
/tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmssPool.h:7: Warning 201: Unable to find 'string'
/tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmssPool.h:8: Warning 201: Unable to find 'future'
/tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmssPool.h:9: Warning 201: Unable to find 'deque'
/tmp/pip-build-xryxolzn/pyqrllib/src/qrl/xmssPool.h:10: Warning 201: Unable to find 'memory'

**Comment by cyyber** [comment]
The issue is with the gcc and g++ version. You must have atleast gcc and g++ version 5

Please follow the steps and you will be able to install in Ubuntu 14.04.5 

sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-5 g++-5

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 1

after the above, you will be able to install qrl

But make sure you have atleast python3.5

**Comment by darcymei** [comment]
Hi Mrwh0, I have met the same problem, how did you close it? Many thanks.
