### ISSUE TITLE
Token balances and Transactions are delayed in gRPC API Calls

### ISSUE THREAD

**Issue by scottdonaldau** [theQRL/QRL#768]
Consider moving token state to bufferedChain so getAddressState gRPC calls get token balances faster.

**Comment by scottdonaldau** [comment]
Tokens Transfer transactions also take some time to appear in getAddressState.

**Comment by scottdonaldau** [comment]
Normal Quanta Transfers are also delayed by a few minutes.

**Comment by cyyber** [comment]
Fixed in PoW
