### ISSUE TITLE
Can send NULL tokens to NULL address

### ISSUE THREAD

**Issue by scottdonaldau** [theQRL/QRL#771]
I was able to send NULL tokens to a NULL address in txn 94cd621e3eeabb2074da9c2add51470ded62bc8d2ffa295469df6500bf459162

**Comment by jleni** [comment]
@cyyber is it possible to close this one?

**Comment by jleni** [comment]
We need help checking if the bug is still reproducible. In that case, a fix would be ideal.

**Comment by cyyber** [comment]
Fixed in PR #1242
