### ISSUE TITLE
Why not python3?

### ISSUE THREAD

**Issue by EcmaXp** [theQRL/QRL#88]
Comment is same as title.

Check the https://pythonclock.org/
You can 2 year and 9 month are lefted for supporting python 2.7

`2to3` tool may help porting 2.7 to 3.x, try use!

Python 3.x support library
- [x] python-dev
- [x] jsonpickle
- [x] leveldb
- [x] beautifulsoup4
- [x] blessings
- [x] statistics (yes, that was a python 3.x module; backported!)
- [x] service_identity
- [x] ntplib

I think only ntplib are not support python3
(but you can porting ntplib also...)

Thanks for reading this issue.

**Comment by surg0r** [comment]
Thanks we are migrating to python 3

**Comment by juharris** [comment]
Damn you stole my plan to mine faster than everyone else :P

**Comment by sammy007** [comment]
Why python?

**Comment by jleni** [comment]
@sammy007 We are currently working on moving critical code to C/C++
@EcmaXp The migration to python3 will happen very soon

**Comment by sammy007** [comment]
June 2017

> Public testnet
> Node optimisation with C++. Golang node creation.
> Internode encrypted communication (‘new hope’ lattice-based cryptography)

Skeleton waiting.

**Comment by jleni** [comment]
The project has now been ported to python3 and the C++ library has been integrated.
