### ISSUE TITLE
Encryption of wallet file

### ISSUE THREAD

**Issue by seanlis** [theQRL/QRL#900]
The wallet file generated by python client is not encrypted.
It would be better to allow users to set a password for accessing this wallet file.

**Comment by jleni** [comment]
Support for encryption is there. CLI needs to be updated.

**Comment by jleni** [comment]
@cyyber CLI support is complete?
@randomshinichi remember to close this issue once the unit tests for this feature are ready.

**Comment by jleni** [comment]
Sorry, CLI adjustments are tracked by issue #1120 
It is possible to close this issue
