### ISSUE TITLE
Add a CLI function to remove a wallet.

### ISSUE THREAD

**Issue by noremac2007** [theQRL/QRL#918]
Manually removing a wallet address from wallet.qrl creates an issue where wallet_add and wallet_ls cannot see the wallets.

Please add a cli function to remove a wallet as needed.

`noremac@ubuntu:~$ qrl wallet_ls
It was not possible to open the wallet: Error parsing message
No wallet found at /home/noremac
`

**Comment by som-dev** [comment]
I think I can work on this one as a "Help Wanted" to help me get more familiar with the system.  Is there a preferred command like maybe "wallet_rm" ?  Since this is removing an address I was thinking about adding an "are you sure" prompt with an optional way to skip the prompt.

**Comment by jleni** [comment]
yes, sounds like a good idea.. maybe a -y to avoid that prompt too?
Be warn that we've changed a bit things... we are merging a lot of new features/changes in the next hour. Address format has changed a bit, too.

**Comment by som-dev** [comment]
Okay, thanks for the heads up.  Maybe I'll wait and merge first before I get into it.  Would wallet-index be sufficient (like wallet_secret) or do you think it should support index and address?
