### ISSUE TITLE
Remove the optional "Type" property from the Transaction message definition in qrl.proto

### ISSUE THREAD

**Issue by ademcan** [theQRL/QRL#922]
It seems that the "Type" property from the Transaction message definition in qrl.proto is optional (from @jleni), we could remove it to make it less ambiguous.
see https://github.com/theQRL/QRL/blob/0b91299ad4fc672fb64610392d541bd3d84de28c/qrl/protos/qrl.proto#L364

**Comment by cyyber** [comment]
Removed in PR #929
