### ISSUE TITLE
qrl wallet_gen - No command 'qrl' found, did you mean:

### ISSUE THREAD

**Issue by markcross** [theQRL/QRL#937]
Installing BETA: on LXLE - Ubuntu 16.04 derrivative

> mark@work:~ qrl wallet_gen
> No command 'qrl' found, did you mean:
>  Command 'qrls' from package 'torque-client' (universe)
>  Command 'qrls' from package 'slurm-wlm-torque' (universe)
>  Command 'qrls' from package 'torque-client-x11' (universe)
>  Command 'qrls' from package 'gridengine-client' (universe)
>  Command 'erl' from package 'erlang-base-hipe' (universe)
>  Command 'erl' from package 'erlang-base' (main)
>  Command 'qrq' from package 'qrq' (universe)
>  Command 'qr' from package 'python-qrcode' (universe)
>  Command 'qml' from package 'qtchooser' (main)
> qrl: command not found
> mark@work:~

https://bugs.launchpad.net/ubuntu/+source/bash/+bug/1588562

`cd ~`

`vi .profile`

**ADD:**

`export PATH="$PATH:$HOME/.local/bin"`

**Comment by jleni** [comment]
This seems to have been fixed in Ubuntu. The issue serves as a reference for future users.
