### ISSUE TITLE
Linking issues result in `Fatal Python errord`

### ISSUE THREAD

**Issue by gokulsan** [theQRL/QRL#939]
I have installed the Quantum Resistant Ledger on my MacOS 10.13.2 as per the instructions provided in the following GitHub repository URL:

`https://github.com/theQRL/QRL`

However it is not starting up when I give the following instructions :

`qml_wallet_gen`

I am getting the following error while I am executing the command :

`Fatal Python error: PyThreadState_Get: no current thread

Abort trap: 6`

Can anybody advise me to resolve this issue. Is this issue related to the local python version.

**Comment by jleni** [comment]
This is actually a python installation problem. This typically happen when you have several python distributions in the same system.. Like system+brew+anaconda, etc.

You are using to run the application a version of Python that is not binary compatible with the one that was in the path when you compiled the Python bindings.

I would suggest using https://docs.python.org/3/library/venv.html to create a virtual environment before installing.

**Comment by jleni** [comment]
This seems to be connected to this issue
https://gitlab.kitware.com/cmake/cmake/issues/17546
