### ISSUE TITLE
Differentiate between installed version and running version

### ISSUE THREAD

**Issue by jleni** [theQRL/QRL#941]
In some cases, the version shown in the log files may not correspond to the actually running version.
Version detection should be improved to recognize local checkouts, etc. 

something like https://github.com/warner/python-versioneer may be useful.

**Comment by randomshinichi** [comment]
I installed versioneer, but it's not working somehow...
https://github.com/warner/python-versioneer/issues/179

**Comment by jleni** [comment]
Functionality added in PR #1234
