### ISSUE TITLE
"Connect Failed" on Slave Generation

### ISSUE THREAD

**Issue by Ompanime** [theQRL/QRL#964]
This is the command that I ran and the result thereof (Please note I am now working on a computer that meets the requirements of running a QRL node.):

`Ompanime@DESKTOP-4H33NIU:~$ qrl -r --host 104.251.219.215 slave_tx_generate
Src []: 0
Addr from (Leave blank in case same as source) []:
Number of slaves [0]: 4
Access type [0]: 1
Fee [0.0]: 0
Generating Slave #1
Successfully Generated Slave 1/4
Generating Slave #2
Successfully Generated Slave 2/4
Generating Slave #3
Successfully Generated Slave 3/4
Generating Slave #4
Successfully Generated Slave 4/4
Connect Failed
Ompanime@DESKTOP-4H33NIU:~$`

**Comment by cyyber** [comment]
Connection Failed means, the IP is not running the services. In such a case feel free to use some different IP.
You may use one of the following
104.251.219.215
104.251.219.145
104.251.219.40
104.237.3.185
104.237.3.184
