### ISSUE TITLE
QRL does not start after update to 0.61.2

### ISSUE THREAD

**Issue by panart117** [theQRL/QRL#978]
# pip3 install -U qrl
Collecting qrl
  Downloading qrl-0.61.2.tar.gz (300kB)
    100% |████████████████████████████████| 307kB 3.3MB/s
Requirement already up-to-date: setuptools>=28.0.0 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: leveldb==0.20 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: ntplib>=0.3.3 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: Twisted>=17.5.0 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: colorlog>=3.0.1 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: simplejson>=3.11.1 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: PyYAML==3.12 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: grpcio-tools<=1.10.0,>=1.9.0 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: grpcio<=1.10.0,>=1.9.0 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: service_identity in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: protobuf in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: pyopenssl>=17.3.0 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: six>=1.9 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: click==6.7 in /usr/local/lib/python3.5/dist-packages (from qrl)
Collecting pyqrllib<0.9.0,>=0.8.1 (from qrl)
  Downloading pyqrllib-0.8.9.tar.gz (219kB)
    100% |████████████████████████████████| 225kB 4.4MB/s
Collecting pyqryptonight<0.8.0,>=0.7.1 (from qrl)
  Downloading pyqryptonight-0.7.2.tar.gz (355kB)
    100% |████████████████████████████████| 358kB 3.5MB/s
Requirement already up-to-date: constantly>=15.1 in /usr/local/lib/python3.5/dist-packages (from Twisted>=17.5.0->qrl)
Requirement already up-to-date: incremental>=16.10.1 in /usr/local/lib/python3.5/dist-packages (from Twisted>=17.5.0->qrl)
Collecting hyperlink>=17.1.1 (from Twisted>=17.5.0->qrl)
  Downloading hyperlink-18.0.0-py2.py3-none-any.whl
Requirement already up-to-date: Automat>=0.3.0 in /usr/local/lib/python3.5/dist-packages (from Twisted>=17.5.0->qrl)
Requirement already up-to-date: zope.interface>=4.0.2 in /usr/local/lib/python3.5/dist-packages (from Twisted>=17.5.0->qrl)
Requirement already up-to-date: pyasn1 in /usr/local/lib/python3.5/dist-packages (from service_identity->qrl)
Requirement already up-to-date: pyasn1-modules in /usr/local/lib/python3.5/dist-packages (from service_identity->qrl)
Requirement already up-to-date: attrs in /usr/local/lib/python3.5/dist-packages (from service_identity->qrl)
Requirement already up-to-date: cryptography>=2.1.4 in /usr/local/lib/python3.5/dist-packages (from pyopenssl>=17.3.0->qrl)
Requirement already up-to-date: scikit-build in /usr/local/lib/python3.5/dist-packages (from pyqrllib<0.9.0,>=0.8.1->qrl)
Requirement already up-to-date: idna>=2.5 in /usr/local/lib/python3.5/dist-packages (from hyperlink>=17.1.1->Twisted>=17.5.0->qrl)
Requirement already up-to-date: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python3.5/dist-packages (from cryptography>=2.1.4->pyopenssl>=17.3.0->qrl)
Requirement already up-to-date: asn1crypto>=0.21.0 in /usr/local/lib/python3.5/dist-packages (from cryptography>=2.1.4->pyopenssl>=17.3.0->qrl)
Requirement already up-to-date: wheel>=0.29.0 in /usr/local/lib/python3.5/dist-packages (from scikit-build->pyqrllib<0.9.0,>=0.8.1->qrl)
Requirement already up-to-date: pycparser in /usr/local/lib/python3.5/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=2.1.4->pyopenssl>=17.3.0->qrl)
Building wheels for collected packages: qrl, pyqrllib, pyqryptonight
  Running setup.py bdist_wheel for qrl ... done
  Stored in directory: /root/.cache/pip/wheels/99/0d/54/1db6e525da51584ad12044ceed6f2719ff7e7c01034c288def
  Running setup.py bdist_wheel for pyqrllib ... done
  Stored in directory: /root/.cache/pip/wheels/c5/69/45/18642e4c56b7340f06cf28faffe6dd2fa2bd399736256a396c
  Running setup.py bdist_wheel for pyqryptonight ... done
  Stored in directory: /root/.cache/pip/wheels/dc/74/87/5499f7088bff74b59d4b5af652b1298205bf5994f90499e8da
Successfully built qrl pyqrllib pyqryptonight
Installing collected packages: pyqrllib, pyqryptonight, qrl, hyperlink
  Found existing installation: pyqrllib 0.5.2
    Uninstalling pyqrllib-0.5.2:
      Successfully uninstalled pyqrllib-0.5.2
  Found existing installation: pyqryptonight 0.6.5
    Uninstalling pyqryptonight-0.6.5:
      Successfully uninstalled pyqryptonight-0.6.5
  Found existing installation: qrl 0.60.7
    Uninstalling qrl-0.60.7:
      Successfully uninstalled qrl-0.60.7
  Found existing installation: hyperlink 17.3.1
    Uninstalling hyperlink-17.3.1:
      Successfully uninstalled hyperlink-17.3.1
Successfully installed hyperlink-18.0.0 pyqrllib-0.8.9 pyqryptonight-0.7.2 qrl-0.61.2
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

# -remove old data

root@v22018025768261189:~/.qrl# rm wallet.qrl
root@v22018025768261189:~/.qrl# rm slaves.json
root@v22018025768261189:~/.qrl# rm banned_peers.qrl

root@v22018025768261189:~/.qrl# qrl wallet_gen
0       010600caa588785ee279c78717afbd935c9fa161a21464e5b5502f4b7b4e796b5c3b3789084acb?

 # generate slaves

root@v22018025768261189:~/.qrl# qrl -r --host  104.237.3.185 slave_tx_generate
Src []: 0
Addr from (Leave blank in case same as source) []:
Number of slaves [0]: 1
Access type [0]: 1
Fee [0.0]:
Generating Slave #1
Successfully Generated Slave 1/1
Successfully created slaves.json
Move slaves.json file from current directory to the mining node inside ~/.qrl/

# Then QRL does not start anymore
start_qrl

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 472, in _ConvertFieldValuePair
    message_descriptor.fields))
google.protobuf.json_format.ParseError: Message type "qrl.BlockHeader" has no field named "timestamp".
 Available Fields(except extensions): <MessageFields sequence>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 530, in _ConvertFieldValuePair
    self.ConvertMessage(value, sub_message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 435, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 537, in _ConvertFieldValuePair
    raise ParseError(str(e))
google.protobuf.json_format.ParseError: Message type "qrl.BlockHeader" has no field named "timestamp".
 Available Fields(except extensions): <MessageFields sequence>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/start_qrl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/qrl/main.py", line 139, in main
    persistent_state = State()
  File "/usr/local/lib/python3.5/dist-packages/qrl/core/State.py", line 545, in __init__
    self.state_objects = StateObjects(self._db)
  File "/usr/local/lib/python3.5/dist-packages/qrl/core/State.py", line 331, in __init__
    db=db)
  File "/usr/local/lib/python3.5/dist-packages/qrl/core/State.py", line 32, in __init__
    self._block_number = Block.from_json(json_data).block_number
  File "/usr/local/lib/python3.5/dist-packages/qrl/core/Block.py", line 83, in from_json
    Parse(json_data, pbdata)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 389, in Parse
    return ParseDict(js, message, ignore_unknown_fields)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 404, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 435, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 535, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse header field: Message type "qrl.BlockHeader" has no field named "timestamp".
 Available Fields(except extensions): <MessageFields sequence>`

**Comment by panart117** [comment]
Still does not start at 0.61.3

Proceed (y/n)? y
  Successfully uninstalled qrl-0.61.3
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


root@v22018025768261189:/usr/local/bin# pip3 install -U qrl
Collecting qrl
Requirement already up-to-date: six>=1.9 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: PyYAML==3.12 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: pyqrllib<0.9.0,>=0.8.1 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: ntplib>=0.3.3 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: setuptools>=28.0.0 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: service-identity in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: grpcio-tools<=1.10.0,>=1.9.0 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: protobuf in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: colorlog>=3.0.1 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: pyqryptonight<0.8.0,>=0.7.1 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: Twisted>=17.5.0 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: simplejson>=3.11.1 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: click==6.7 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: grpcio<=1.10.0,>=1.9.0 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: pyopenssl>=17.3.0 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: leveldb==0.20 in /usr/local/lib/python3.5/dist-packages (from qrl)
Requirement already up-to-date: scikit-build in /usr/local/lib/python3.5/dist-packages (from pyqrllib<0.9.0,>=0.8.1->qrl)
Requirement already up-to-date: pyasn1 in /usr/local/lib/python3.5/dist-packages (from service-identity->qrl)
Requirement already up-to-date: pyasn1-modules in /usr/local/lib/python3.5/dist-packages (from service-identity->qrl)
Requirement already up-to-date: attrs in /usr/local/lib/python3.5/dist-packages (from service-identity->qrl)
Requirement already up-to-date: incremental>=16.10.1 in /usr/local/lib/python3.5/dist-packages (from Twisted>=17.5.0->qrl)
Requirement already up-to-date: Automat>=0.3.0 in /usr/local/lib/python3.5/dist-packages (from Twisted>=17.5.0->qrl)
Requirement already up-to-date: hyperlink>=17.1.1 in /usr/local/lib/python3.5/dist-packages (from Twisted>=17.5.0->qrl)
Requirement already up-to-date: zope.interface>=4.0.2 in /usr/local/lib/python3.5/dist-packages (from Twisted>=17.5.0->qrl)
Requirement already up-to-date: constantly>=15.1 in /usr/local/lib/python3.5/dist-packages (from Twisted>=17.5.0->qrl)
Requirement already up-to-date: cryptography>=2.1.4 in /usr/local/lib/python3.5/dist-packages (from pyopenssl>=17.3.0->qrl)
Requirement already up-to-date: wheel>=0.29.0 in /usr/local/lib/python3.5/dist-packages (from scikit-build->pyqrllib<0.9.0,>=0.8.1->qrl)
Requirement already up-to-date: idna>=2.5 in /usr/local/lib/python3.5/dist-packages (from hyperlink>=17.1.1->Twisted>=17.5.0->qrl)
Requirement already up-to-date: asn1crypto>=0.21.0 in /usr/local/lib/python3.5/dist-packages (from cryptography>=2.1.4->pyopenssl>=17.3.0->qrl)
Requirement already up-to-date: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python3.5/dist-packages (from cryptography>=2.1.4->pyopenssl>=17.3.0->qrl)
Requirement already up-to-date: pycparser in /usr/local/lib/python3.5/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=2.1.4->pyopenssl>=17.3.0->qrl)
Installing collected packages: qrl
Successfully installed qrl-0.61.3
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.



root@v22018025768261189:/usr/local/bin# start_qrl
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 472, in _ConvertFieldValuePair
    message_descriptor.fields))
google.protobuf.json_format.ParseError: Message type "qrl.Transaction" has no field named "type".
 Available Fields(except extensions): <MessageFields sequence>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 515, in _ConvertFieldValuePair
    self.ConvertMessage(item, sub_message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 435, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 537, in _ConvertFieldValuePair
    raise ParseError(str(e))
google.protobuf.json_format.ParseError: Message type "qrl.Transaction" has no field named "type".
 Available Fields(except extensions): <MessageFields sequence>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/start_qrl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/qrl/main.py", line 139, in main
    persistent_state = State()
  File "/usr/local/lib/python3.5/dist-packages/qrl/core/State.py", line 545, in __init__
    self.state_objects = StateObjects(self._db)
  File "/usr/local/lib/python3.5/dist-packages/qrl/core/State.py", line 331, in __init__
    db=db)
  File "/usr/local/lib/python3.5/dist-packages/qrl/core/State.py", line 32, in __init__
    self._block_number = Block.from_json(json_data).block_number
  File "/usr/local/lib/python3.5/dist-packages/qrl/core/Block.py", line 83, in from_json
    Parse(json_data, pbdata)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 389, in Parse
    return ParseDict(js, message, ignore_unknown_fields)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 404, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 435, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/json_format.py", line 535, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse transactions field: Message type "qrl.Transaction" has no field named "type".
 Available Fields(except extensions): <MessageFields sequence>

**Comment by cyyber** [comment]
Please make sure you have deleted ~/.qrl/data
Because we have hard forked the network, and old blocks or chain or wallet will not be supported.

**Comment by jleni** [comment]
Similar to #674
