### ISSUE TITLE
"Connect Failed" error after generating slaves

### ISSUE THREAD

**Issue by ghost** [theQRL/QRL#980]
-v0.61.2
-ubuntu 16.04 LTS, 64-bit
-Virtual Box

```
Generating Slave #1
Successfully Generated Slave 1/2
Generating Slave #2
Successfully Generated Slave 2/2
Connect Failed
```

**Comment by cyyber** [comment]
Please use a different ip such as 
104.237.3.185
104.237.3.184
104.251.219.40
104.251.219.145

Issue same as #964

**Comment by ghost** [comment]
running smoothly now, thanks cyyber
