### ISSUE TITLE
qrl wallet_secret doesn't show Q before address

### ISSUE THREAD

**Issue by plebcity** [theQRL/QRL#983]
The wallet_secret only shows: 
Wallet Address  : 010600157269b89997954299fbd2e5e37e3b9274b646cfdc6a97666ee7d4320aa808727465ce7c
Mnemonic        : .....
Hexseed         : .....

There needs to be a Q in front of the address

**Comment by plebcity** [comment]
Hexseed also doesn't have a Q, not sure if it's supposed to have one.

**Comment by cyyber** [comment]
Hexseed never have Q in it. But yes we are missing prepending Q while showing wallet Address. Basically its an UI issue, which will be fixed in upcoming version.

**Comment by cyyber** [comment]
Fixed in PR #988 
will be released in v0.61.4 with other fixes.
